Repository FoalTS/foal, pull requests merged in 2018-12, with the labels that each got.

#282 [docs] Add API reference for each package
  docs/SUMMARY.md
  docs/api/core/api/index.md
  docs/api/core/api/index/abstractuser.md
  docs/api/core/api/index/config.md
  docs/api/core/api/index/context.md
  docs/api/core/api/index/emailauthenticator.md
  docs/api/core/api/index/entityresourcecollection.md
  docs/api/core/api/index/group.md
  docs/api/core/api/index/httpresponse.md
  docs/api/core/api/index/httpresponsebadrequest.md
  docs/api/core/api/index/httpresponseclienterror.md
  docs/api/core/api/index/httpresponseconflict.md
  docs/api/core/api/index/httpresponsecreated.md
  docs/api/core/api/index/httpresponseforbidden.md
  docs/api/core/api/index/httpresponseinternalservererror.md
  docs/api/core/api/index/httpresponsemethodnotallowed.md
  docs/api/core/api/index/httpresponsenocontent.md
  docs/api/core/api/index/httpresponsenotfound.md
  docs/api/core/api/index/httpresponsenotimplemented.md
  docs/api/core/api/index/httpresponseok.md
  docs/api/core/api/index/httpresponseredirect.md
  docs/api/core/api/index/httpresponseredirection.md
  docs/api/core/api/index/httpresponseservererror.md
  docs/api/core/api/index/httpresponsesuccess.md
  docs/api/core/api/index/httpresponseunauthorized.md
  docs/api/core/api/index/logincontroller.md
  docs/api/core/api/index/objectdoesnotexist.md
  docs/api/core/api/index/permission.md
  docs/api/core/api/index/permissiondenied.md
  docs/api/core/api/index/restcontroller.md
  docs/api/core/api/index/servicemanager.md
  docs/api/core/api/index/validationerror.md
  docs/api/ejs/api/index.md
  docs/api/password/api/index.md
  packages/core/package.json
  packages/ejs/package.json
  packages/password/package.json
  packages/password/tsconfig.json
Labels: docs, enhancement

#284 [@foal/core] Add empty csrfToken function when csrf=false
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
Labels: bug

#272 Add JWT support for authentication
  .gitignore
  docs/authentication-and-access-control/SUMMARY.md
  docs/authentication-and-access-control/jwt.md
  packages/core/.gitignore
  packages/core/src/common/utils/fetch-user.util.spec.ts
  packages/core/src/common/utils/fetch-user.util.ts
  packages/core/src/common/utils/index.ts
  packages/core/src/common/utils/is-in-file.util.spec.ts
  packages/core/src/common/utils/is-in-file.util.ts
  packages/jwt/.gitignore
  packages/jwt/LICENSE
  packages/jwt/README.md
  packages/jwt/e2e/jwt.spec.ts
  packages/jwt/package.json
  packages/jwt/src/index.ts
  packages/jwt/src/jwt-optional.hook.spec.ts
  packages/jwt/src/jwt-optional.hook.ts
  packages/jwt/src/jwt-required.hook.spec.ts
  packages/jwt/src/jwt-required.hook.ts
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
  packages/jwt/tsconfig-build.json
  packages/jwt/tsconfig.json
Labels: feature request

#287 Merge `AuthenticationWithSessionAndCookie` and `LoginRequired` into `LoginRequired`
  docs/architecture/hooks.md
  docs/authentication-and-access-control/usage-in-web-requests.md
  docs/tutorials/multi-user-todo-list/6-todos-and-ownership.md
  docs/tutorials/simple-todo-list/5-the-rest-api.md
  packages/cli/src/generate/specs/app/src/app/app.controller.ts
  packages/cli/src/generate/templates/app/src/app/app.controller.ts
  packages/core/e2e/auth.spec.ts
  packages/core/e2e/rest.spec.ts
  packages/core/src/auth/authentication/authenticate.hook.spec.ts
  packages/core/src/auth/authentication/authenticate.hook.ts
  packages/core/src/auth/authentication/index.ts
  packages/core/src/auth/authorization/index.ts
  packages/core/src/auth/authorization/login-required.hook.spec.ts
  packages/core/src/auth/authorization/login-required.hook.ts
  packages/core/src/auth/index.ts
  packages/core/src/auth/login-optional.hook.spec.ts
  packages/core/src/auth/login-optional.hook.ts
  packages/core/src/auth/login-required.hook.spec.ts
  packages/core/src/auth/login-required.hook.ts
  packages/core/src/auth/login.hook.spec.ts
  packages/core/src/auth/login.hook.ts
  packages/core/src/common/utils/fetch-user-with-permissions.util.spec.ts
  packages/core/src/common/utils/fetch-user-with-permissions.util.ts
  packages/core/src/common/utils/index.ts
  packages/examples/src/app/app.controller.ts
  packages/examples/src/app/controllers/view.controller.ts
Labels: Breaking change, enhancement

#292 Register the controller routes *after* its sub-controllers
  docs/SUMMARY.md
  docs/cookbook/404-page.md
  packages/core/e2e/404.spec.ts
  packages/core/src/core/routes/make-controller-routes.spec.ts
  packages/core/src/core/routes/make-controller-routes.ts
Labels: Breaking change, enhancement

#295 [@foal/cli] Remove the prompts from "foal g controller|service"
  docs/architecture/services.md
  docs/development-environment/code-generation.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  docs/tutorials/multi-user-todo-list/7-the-signup-page.md
  docs/tutorials/simple-todo-list/5-the-rest-api.md
  e2e_test.sh
  packages/cli/package.json
  packages/cli/src/index.ts
Labels: enhancement

#297 Update .gitignore to ignore WebStorm and VSCode config directories
  .gitignore
  packages/cli/src/generate/specs/app/gitignore
  packages/cli/src/generate/templates/app/gitignore
Labels: enhancement
