Repository FoalTS/foal, pull requests merged in 2018-09, with the labels that each got.

#197 Add getCommandLineArguments util and `create-user`, `create-group` and `create-perm` scripts.
  docs/the-authentication-system/authentication.md
  docs/the-authentication-system/permissions-and-authorization.md
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/src/scripts/create-group.ts
  packages/cli/src/generate/specs/app/src/scripts/create-perm.ts
  packages/cli/src/generate/specs/app/src/scripts/create-user.ts
  packages/cli/src/generate/specs/app/src/scripts/create-users.ts
  packages/cli/src/generate/templates/app/src/scripts/create-group.ts
  packages/cli/src/generate/templates/app/src/scripts/create-perm.ts
  packages/cli/src/generate/templates/app/src/scripts/create-user.ts
  packages/cli/src/generate/templates/app/src/scripts/create-users.ts
  packages/core/e2e/auth.spec.ts
  packages/core/src/auth/authentication/authenticate.hook.spec.ts
  packages/core/src/auth/entities/abstract-user.entity.spec.ts
  packages/core/src/auth/entities/group.entity.spec.ts
  packages/core/src/auth/entities/group.entity.ts
  packages/core/src/common/utils/get-command-line-arguments.util.spec.ts
  packages/core/src/common/utils/get-command-line-arguments.util.ts
  packages/core/src/common/utils/index.ts
Labels: feature request

#198 [Internal] Add e2e tests in Travis
  .gitignore
  .travis.yml
  docs/the-authentication-system/permissions-and-authorization.md
  e2e_test.sh
  packages/cli/package.json
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/src/app/controllers/view.controller.spec.ts
  packages/cli/src/generate/specs/app/src/app/controllers/view.controller.ts
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/src/app/controllers/view.controller.spec.ts
  packages/cli/src/generate/templates/app/src/app/controllers/view.controller.ts
Labels: internal

#199 Add the script generator
  docs/development-environment/create-and-run-scripts.md
  e2e_test.sh
  packages/cli/src/generate/generators/index.ts
  packages/cli/src/generate/generators/script/create-script.spec.ts
  packages/cli/src/generate/generators/script/create-script.ts
  packages/cli/src/generate/generators/script/index.ts
  packages/cli/src/generate/specs/script/test-foo-bar.ts
  packages/cli/src/generate/templates/script/script.ts
  packages/cli/src/index.ts
Labels: feature request

#200 Automatically register controllers upon creation.
  README.md
  docs/development-environment/code-generation.md
  packages/cli/src/generate/generators/controller/create-controller.spec.ts
  packages/cli/src/generate/generators/controller/create-controller.ts
  packages/cli/src/generate/generators/controller/register-controller.ts
  packages/cli/src/generate/mocks/controller/app.module.controller-import.ts
  packages/cli/src/generate/mocks/controller/app.module.core-import.ts
  packages/cli/src/generate/mocks/controller/app.module.empty-property.ts
  packages/cli/src/generate/mocks/controller/app.module.empty-spaced-property.ts
  packages/cli/src/generate/mocks/controller/app.module.no-controller-import.ts
  packages/cli/src/generate/mocks/controller/app.module.no-empty-property.ts
  packages/cli/src/generate/mocks/controller/app.module.rest.ts
  packages/cli/src/generate/specs/controller/app.module.controller-import.ts
  packages/cli/src/generate/specs/controller/app.module.core-import.ts
  packages/cli/src/generate/specs/controller/app.module.empty-property.ts
  packages/cli/src/generate/specs/controller/app.module.empty-spaced-property.ts
  packages/cli/src/generate/specs/controller/app.module.no-controller-import.ts
  packages/cli/src/generate/specs/controller/app.module.no-empty-property.ts
  packages/cli/src/generate/specs/controller/app.module.rest.ts
  packages/cli/src/generate/utils/generator.ts
  packages/cli/src/index.ts
  tslint.json
Labels: enhancement, feature request

#202 Add the `foal run-script` feature.
  docs/development-environment/create-and-run-scripts.md
  docs/the-authentication-system/permissions-and-authorization.md
  e2e_test.sh
  packages/cli/package.json
  packages/cli/src/generate/specs/app/src/scripts/create-group.ts
  packages/cli/src/generate/specs/app/src/scripts/create-perm.ts
  packages/cli/src/generate/specs/app/src/scripts/create-user.ts
  packages/cli/src/generate/specs/script/test-foo-bar.ts
  packages/cli/src/generate/templates/app/src/scripts/create-group.ts
  packages/cli/src/generate/templates/app/src/scripts/create-perm.ts
  packages/cli/src/generate/templates/app/src/scripts/create-user.ts
  packages/cli/src/generate/templates/script/script.ts
  packages/cli/src/index.ts
  packages/cli/src/run-script.spec.ts
  packages/cli/src/run-script.ts
  packages/core/src/common/utils/get-command-line-arguments.util.spec.ts
  packages/core/src/common/utils/get-command-line-arguments.util.ts
Labels: feature request

#201 Update session default configuration following OWASP recommandations
  docs/deployment-and-environments/ship-to-production.md
  packages/cli/src/generate/specs/app/config/settings.production.json
  packages/cli/src/generate/templates/app/config/settings.production.json
Labels: enhancement

#206 Correcting typeorm scripts - Issue #204
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/templates/app/package.json
  packages/examples/package.json
Labels: bug

#219 Make the tests run with NODE_ENV=test (on Unix/Windows)
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/src/test.ts
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/src/test.ts
Labels: bug

#221 [Docs] Ask to rerun "npm run develop" in the guide.
  docs/guide/1-introduction.md
Labels: enhancement

#230 Add some docs in the contribution guidelines.
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.MD
Labels: enhancement

#234 Set `strictPropertyInitialization` to `false` in `tsconfig.json` and remove the `ts-ignore`.
  docs/guide/3-flight-model.md
  docs/the-authentication-system/authentication.md
  packages/cli/src/generate/specs/app/src/app/entities/user.entity.ts
  packages/cli/src/generate/specs/app/tsconfig.json
  packages/cli/src/generate/specs/entity/test-foo-bar.entity.ts
  packages/cli/src/generate/templates/app/src/app/entities/user.entity.ts
  packages/cli/src/generate/templates/app/tsconfig.json
  packages/cli/src/generate/templates/entity/entity.ts
  packages/cli/tsconfig.json
  packages/core/e2e/auth.spec.ts
  packages/core/e2e/rest.spec.ts
  packages/core/src/auth/authentication/authenticate.hook.spec.ts
  packages/core/src/auth/authentication/strategies/email/email-authenticator.service.spec.ts
  packages/core/src/auth/entities/abstract-user.entity.ts
  packages/core/src/auth/entities/group.entity.ts
  packages/core/src/auth/entities/permission.entity.ts
  packages/core/src/common/services/entity-resource-collection.service.spec.ts
  packages/core/tsconfig.json
  packages/ejs/tsconfig.json
  packages/password/tsconfig.json
Labels: enhancement

#235 Simplify shell scripts
  README.md
  e2e_test.sh
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/generate/specs/app/src/scripts/create-group.ts
  packages/cli/src/generate/specs/app/src/scripts/create-perm.ts
  packages/cli/src/generate/specs/app/src/scripts/create-user.ts
  packages/cli/src/generate/specs/script/test-foo-bar.ts
  packages/cli/src/generate/templates/app/src/scripts/create-group.ts
  packages/cli/src/generate/templates/app/src/scripts/create-perm.ts
  packages/cli/src/generate/templates/app/src/scripts/create-user.ts
  packages/cli/src/generate/templates/script/script.ts
  packages/cli/src/index.ts
  packages/cli/src/run-script.spec.ts
  packages/cli/src/run-script/get-command-line-arguments.util.spec.ts
  packages/cli/src/run-script/get-command-line-arguments.util.ts
  packages/cli/src/run-script/index.ts
  packages/cli/src/run-script/run-script.spec.ts
  packages/cli/src/run-script/run-script.ts
  packages/core/src/common/utils/index.ts
Labels: feature request

#241 [Docs] Improve documentation and fix failing examples
  docs/README.md
  docs/SUMMARY.md
  docs/architecture/controllers.md
  docs/architecture/services.md
  docs/authentication-and-access-control/SUMMARY.md
  docs/authentication-and-access-control/permissions-and-authorization.md
  docs/authentication-and-access-control/permissions-groups-and-users.png
  docs/authentication-and-access-control/permissions-groups-and-users.xml
  docs/authentication-and-access-control/usage-in-web-requests.md
  docs/authentication-and-access-control/user-entity.md
  docs/cookbook/validation.md
  docs/development-environment/create-and-run-scripts.md
  docs/guide/installation.md
  docs/the-authentication-system/authentication.md
  docs/the-authentication-system/permissions-and-authorization.md
Labels: docs
