Repository FoalTS/foal, pull requests merged in 2019-07, with the labels that each got.

#472 [Docs][Security] Explain how to limit repeated requests to public APIs (Rate Limit middleware)
  docs/SUMMARY.md
  docs/cookbook/limit-repeated-requests.md
Labels: docs

#476 [jwks-rsa] Update insecure package-lock.json
  packages/jwks-rsa/package-lock.json
Labels: enhancement

#483 [Bug] Fix 500 errors on invalid JSON
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/core/src/express/handle-errors.ts
Labels: bug

#484 [Bug] Make `foal generate` not fail if index.ts does not exist
  packages/cli/src/generate/generators/controller/create-controller.spec.ts
  packages/cli/src/generate/generators/controller/create-controller.ts
  packages/cli/src/generate/generators/entity/create-entity.spec.ts
  packages/cli/src/generate/generators/entity/create-entity.ts
  packages/cli/src/generate/generators/hook/create-hook.spec.ts
  packages/cli/src/generate/generators/hook/create-hook.ts
  packages/cli/src/generate/generators/model/create-model.spec.ts
  packages/cli/src/generate/generators/model/create-model.ts
  packages/cli/src/generate/generators/service/create-service.spec.ts
  packages/cli/src/generate/generators/service/create-service.ts
Labels: bug

#487 Prettify error page in dev
  packages/core/src/express/500.debug.html
Labels: enhancement

#492 [Docs] CORS requests with cookies
  docs/api-section/public-api-and-cors-requests.md
Labels: docs

#491 [Docs] Adds CORS example for rate limiting
  docs/api-section/public-api-and-cors-requests.md
  docs/cookbook/limit-repeated-requests.md
Labels: docs

#493 [Docs] Add root imports.
  docs/SUMMARY.md
  docs/cookbook/root-imports.md
Labels: docs

#498 Revert "Add swagger ui config"
  package-lock.json
  packages/swagger/package-lock.json
  packages/swagger/src/index.controller.spec.html
  packages/swagger/src/index.no-primary.spec.html
  packages/swagger/src/index.no-primary.ui-options.spec.html
  packages/swagger/src/index.primary.spec.html
  packages/swagger/src/index.tpl.html
  packages/swagger/src/index.url.spec.html
  packages/swagger/src/index.url.ui-options.spec.html
  packages/swagger/src/swagger-controller.spec.ts
  packages/swagger/src/swagger-controller.ts
Labels: internal
