Repository FoalTS/foal, pull requests merged in 2019-02, with the labels that each got.

#345 [@foal/cli] Validate params in REST APIs
  e2e_test.sh
  packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.current-dir.ts
  packages/cli/src/generate/specs/rest-api/test-foo-bar.controller.ts
  packages/cli/src/generate/templates/rest-api/controller.current-dir.ts
  packages/cli/src/generate/templates/rest-api/controller.ts
Labels: enhancement

#347 Allow customized configuration for getAjvInstance
  docs/validation-and-sanitization.md
  packages/core/src/common/utils/get-ajv-instance.spec.ts
  packages/core/src/common/utils/get-ajv-instance.ts
Labels: feature request

#349 [@foal/cli] Make `foal g script` generate scripts from anywhere in the project.
  docs/development-environment/code-generation.md
  packages/cli/src/generate/generators/script/create-script.spec.ts
  packages/cli/src/generate/generators/script/create-script.ts
Labels: enhancement

#348 Have CLI commands to quickly connect a Vue/React/Angular frontend to the backend (dev & prod)
  README.md
  docs/SUMMARY.md
  docs/deployment-and-environments/configuration.md
  docs/frontend-integration/angular-react-vue.md
  docs/frontend-integration/single-page-applications.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  docs/tutorials/simple-todo-list/1-installation.md
  e2e_test.sh
  packages/cli/README.md
  packages/cli/src/generate/generators/angular/connect-angular.spec.ts
  packages/cli/src/generate/generators/angular/connect-angular.ts
  packages/cli/src/generate/generators/angular/index.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/generators/index.ts
  packages/cli/src/generate/generators/react/connect-react.spec.ts
  packages/cli/src/generate/generators/react/connect-react.ts
  packages/cli/src/generate/generators/react/index.ts
  packages/cli/src/generate/generators/vue/connect-vue.spec.ts
  packages/cli/src/generate/generators/vue/connect-vue.ts
  packages/cli/src/generate/generators/vue/index.ts
  packages/cli/src/generate/mocks/angular/angular.json
  packages/cli/src/generate/mocks/angular/package.json
  packages/cli/src/generate/mocks/react/package.json
  packages/cli/src/generate/mocks/vue/package.json
  packages/cli/src/generate/specs/angular/angular.json
  packages/cli/src/generate/specs/angular/package.json
  packages/cli/src/generate/specs/angular/proxy.conf.json
  packages/cli/src/generate/specs/app/config/settings.json
  packages/cli/src/generate/specs/app/src/index.mongodb.ts
  packages/cli/src/generate/specs/app/src/index.ts
  packages/cli/src/generate/specs/react/package.json
  packages/cli/src/generate/specs/vue/package.json
  packages/cli/src/generate/templates/angular/proxy.conf.json
  packages/cli/src/generate/templates/app/config/settings.json
  packages/cli/src/generate/templates/app/src/index.mongodb.ts
  packages/cli/src/generate/templates/app/src/index.ts
  packages/cli/src/generate/utils/test-environment.ts
  packages/cli/src/index.ts
  packages/core/README.md
  packages/core/src/express/create-app.ts
  packages/ejs/README.md
  packages/examples/config/settings.json
  packages/examples/src/index.ts
  packages/jwt/README.md
  packages/mongoose/README.md
  packages/password/README.md
  packages/typeorm/README.md
Labels: feature request

#356 Fix config order issue (v0.8.1)
  lerna.json
  packages/core/package.json
  packages/core/src/core/config.spec.ts
  packages/core/src/core/config.ts
  packages/examples/package.json
  packages/jwt/package.json
  packages/mongoose/package.json
  packages/typeorm/package.json
Labels: bug

#364 fix of issue #361
  docs/tutorials/mongodb-todo-list/5-the-rest-api.md
Labels: bug, docs
