Repository FoalTS/foal, pull requests merged in 2019-01, with the labels that each got.

#300 Provide two util functions encryptPassword and verifyPassword to manage password encryption
  docs/authentication-and-access-control/user-entity.md
  docs/tutorials/multi-user-todo-list/2-the-user-and-todo-models.md
  packages/cli/src/generate/specs/app/src/app/entities/user.entity.ts
  packages/cli/src/generate/templates/app/src/app/entities/user.entity.ts
  packages/core/src/auth/utils/encrypt-password.util.spec.ts
  packages/core/src/auth/utils/encrypt-password.util.ts
  packages/core/src/auth/utils/index.ts
  packages/core/src/auth/utils/parse-password.parser.spec.ts
  packages/core/src/auth/utils/parse-password.parser.ts
  packages/core/src/auth/utils/verify-password.util.spec.ts
  packages/core/src/auth/utils/verify-password.util.ts
  packages/core/src/common/index.ts
  packages/examples/src/app/entities/user.entity.ts
  packages/typeorm/e2e/auth.spec.ts
Labels: Breaking change, enhancement, feature request

#294 [Docs] Reorganize the "Topic guides" section and update docs to v0.7.0
  docs/SUMMARY.md
  docs/api-section/public-api-and-cors-requests.md
  docs/api-section/rest-blueprints.md
  docs/api-section/rest-controllers.md
  docs/architecture/architecture-example.png
  docs/architecture/architecture-example.xml
  docs/architecture/architecture-overview.md
  docs/architecture/controllers.md
  docs/architecture/hooks.md
  docs/architecture/request-lifecycle.md
  docs/architecture/request_lifecycle.png
  docs/architecture/request_lifecycle.xml
  docs/architecture/services-and-dependency-injection.md
  docs/architecture/services.md
  docs/authentication-and-access-control/SUMMARY.md
  docs/authentication-and-access-control/administrators-and-roles.md
  docs/authentication-and-access-control/groups-and-permissions.md
  docs/authentication-and-access-control/introduction.md
  docs/authentication-and-access-control/jwt.md
  docs/authentication-and-access-control/password-management.md
  docs/authentication-and-access-control/permissions-and-authorization.md
  docs/authentication-and-access-control/session-and-cookie.md
  docs/authentication-and-access-control/usage-in-web-requests.md
  docs/authentication-and-access-control/user-class.md
  docs/authentication-and-access-control/user-entity.md
  docs/cookbook/basic-logging.md
  docs/databases/create-models-and-queries.md
  docs/databases/generate-and-run-migrations.md
  docs/databases/introduction.md
  docs/databases/typeorm.md
  docs/security/csrf-protection.md
  docs/testing/unit-testing.md
  docs/utilities/logging-and-debugging.md
  docs/utilities/templating.md
  docs/validation.md
  packages/core/src/core/service-manager.ts
Labels: docs, enhancement

#305 Be able to customize the logger outputs
  docs/utilities/logging-and-debugging.md
  packages/cli/src/generate/specs/app/config/settings.development.json
  packages/cli/src/generate/specs/app/config/settings.json
  packages/cli/src/generate/templates/app/config/settings.development.json
  packages/cli/src/generate/templates/app/config/settings.json
  packages/core/src/express/create-app.ts
Labels: enhancement, feature request

#309 Validate arguments for createapp command
  packages/cli/package-lock.json
  packages/cli/src/index.ts
Labels: enhancement

#307 Validates random commands and shows up help if none supplied
  packages/cli/src/index.ts
Labels: enhancement

#316 [@foal/cli] Add `foal run` as alias of `foal run-script`
  docs/authentication-and-access-control/groups-and-permissions.md
  docs/authentication-and-access-control/user-class.md
  docs/development-environment/create-and-run-scripts.md
  docs/tutorials/mongodb-todo-list/2-with-typeorm.md
  docs/tutorials/multi-user-todo-list/3-the-shell-scripts.md
  docs/tutorials/simple-todo-list/4-the-shell-script-create-todo.md
  e2e_test.sh
  packages/cli/src/index.ts
Labels: enhancement

#315 [@foal/cli] Refactor `createapp` command to generate files closest to an SPA.
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  docs/tutorials/multi-user-todo-list/7-the-signup-page.md
  docs/tutorials/multi-user-todo-list/8-e2e-testing-and-authentication.md
  docs/tutorials/simple-todo-list/2-introduction.md
  docs/tutorials/simple-todo-list/5-the-rest-api.md
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/config/app.development.json
  packages/cli/src/generate/specs/app/config/app.e2e.json
  packages/cli/src/generate/specs/app/config/app.production.json
  packages/cli/src/generate/specs/app/config/app.test.json
  packages/cli/src/generate/specs/app/config/settings.json
  packages/cli/src/generate/specs/app/config/settings.production.json
  packages/cli/src/generate/specs/app/public/index.html
  packages/cli/src/generate/specs/app/src/app/app.controller.ts
  packages/cli/src/generate/specs/app/src/app/controllers/api.controller.spec.ts
  packages/cli/src/generate/specs/app/src/app/controllers/api.controller.ts
  packages/cli/src/generate/specs/app/src/app/controllers/index.ts
  packages/cli/src/generate/specs/app/src/app/controllers/view.controller.spec.ts
  packages/cli/src/generate/specs/app/src/app/controllers/view.controller.ts
  packages/cli/src/generate/templates/app/config/app.development.json
  packages/cli/src/generate/templates/app/config/app.e2e.json
  packages/cli/src/generate/templates/app/config/app.production.json
  packages/cli/src/generate/templates/app/config/app.test.json
  packages/cli/src/generate/templates/app/config/settings.json
  packages/cli/src/generate/templates/app/config/settings.production.json
  packages/cli/src/generate/templates/app/public/index.html
  packages/cli/src/generate/templates/app/src/app/app.controller.ts
  packages/cli/src/generate/templates/app/src/app/controllers/api.controller.spec.ts
  packages/cli/src/generate/templates/app/src/app/controllers/api.controller.ts
  packages/cli/src/generate/templates/app/src/app/controllers/index.ts
  packages/cli/src/generate/templates/app/src/app/controllers/view.controller.spec.ts
  packages/cli/src/generate/templates/app/src/app/controllers/view.controller.ts
  packages/core/src/express/create-app.ts
Labels: enhancement

#317 [@foal/cli] `foal createapp`: prettify the outputs and auto initialize git repo.
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/utils/generator.ts
  packages/cli/src/generate/utils/index.ts
  packages/cli/src/generate/utils/init-git-repo.ts
  packages/cli/src/index.ts
Labels: enhancement, feature request

#325 Fix type error in JWTOptional and JWTRequired
  e2e_test.sh
  packages/jwt/src/jwt-optional.hook.ts
  packages/jwt/src/jwt-required.hook.ts
Labels: bug

#326 Validate project name as per npm conventions
  packages/cli/src/generate/generators/app/create-app.ts
Labels: enhancement

#332 Fix typos in the `get-started` tutorial
  docs/tutorials/simple-todo-list/5-the-rest-api.md
  docs/tutorials/simple-todo-list/6-validation-and-sanitization.md
Labels: docs

#334 Automatically parse cookies.
  packages/core/package.json
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
Labels: feature request

#336 Allow `JWTRequired` and `JWTOptional` retrieve the tokens from a cookie
  docs/authentication-and-access-control/jwt.md
  packages/jwt/e2e/jwt.spec.ts
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
Labels: feature request

#337 Add a type to Context.request
  packages/core/package.json
  packages/core/src/common/hooks/validate-headers.hook.spec.ts
  packages/core/src/core/http/contexts.ts
Labels: feature request
