Repository FoalTS/foal, pull requests merged in 2019-05, with the labels that each got.

#419 Fix typo in docu
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
Labels: docs

#415 [Docs] Explain how to deploy a Foal application to AWS Beanstalk (with SQL DB)
  docs/SUMMARY.md
  docs/cloud/aws-beanstalk.md
  docs/cloud/aws1.png
  docs/cloud/aws10.png
  docs/cloud/aws11.png
  docs/cloud/aws12.png
  docs/cloud/aws13.png
  docs/cloud/aws14.png
  docs/cloud/aws15.png
  docs/cloud/aws2.png
  docs/cloud/aws3.png
  docs/cloud/aws4.png
  docs/cloud/aws5.png
  docs/cloud/aws6.png
  docs/cloud/aws7.png
  docs/cloud/aws8.png
  docs/cloud/aws9.png
Labels: docs

#427 Support GraphQL
  docs/SUMMARY.md
  docs/api-section/graphql.md
  packages/acceptance-tests/src/404-page.spec.ts
  packages/acceptance-tests/src/examples/schema.graphql
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/graphql/LICENSE
  packages/graphql/README.md
  packages/graphql/package-lock.json
  packages/graphql/package.json
  packages/graphql/src/acceptance-test.spec.ts
  packages/graphql/src/format-error.decorator.spec.ts
  packages/graphql/src/format-error.decorator.ts
  packages/graphql/src/format-error.spec.ts
  packages/graphql/src/format-error.ts
  packages/graphql/src/graphql.controller.spec.ts
  packages/graphql/src/graphql.controller.ts
  packages/graphql/src/index.ts
  packages/graphql/src/mask-and-log-error.spec.ts
  packages/graphql/src/mask-and-log-error.ts
  packages/graphql/src/schema-from-type-defs.spec.ts
  packages/graphql/src/schema-from-type-defs.ts
  packages/graphql/src/schema-from-type-glob.spec.ts
  packages/graphql/src/schema-from-type-glob.ts
  packages/graphql/src/schema-from-type-paths.spec.ts
  packages/graphql/src/schema-from-type-paths.ts
  packages/graphql/tsconfig-build.json
  packages/graphql/tsconfig.json
Labels: feature request

#438 Fix invalid data parsing in Config
  packages/core/src/core/config.spec.ts
  packages/core/src/core/config.ts
Labels: bug

#430 Support Auth0 & AWS Cognito (be able to retrieve RSA public key from JWKS endpoint)
  .gitignore
  docs/authentication-and-access-control/jwt.md
  packages/acceptance-tests/package-lock.json
  packages/acceptance-tests/package.json
  packages/acceptance-tests/src/jwks.spec.ts
  packages/acceptance-tests/src/rsa-private.pem
  packages/acceptance-tests/src/rsa-public-key.pem
  packages/jwks-rsa/LICENSE
  packages/jwks-rsa/README.md
  packages/jwks-rsa/package-lock.json
  packages/jwks-rsa/package.json
  packages/jwks-rsa/src/get-rsa-public-key-from-jwks.spec.ts
  packages/jwks-rsa/src/get-rsa-public-key-from-jwks.ts
  packages/jwks-rsa/src/index.ts
  packages/jwks-rsa/tsconfig-build.json
  packages/jwks-rsa/tsconfig.json
  packages/jwt/.gitignore
  packages/jwt/src/index.ts
  packages/jwt/src/invalid-token.error.spec.ts
  packages/jwt/src/invalid-token.error.ts
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
Labels: feature request
