Repository FoalTS/foal, pull requests merged in 2019-10, with the labels that each got.

#551 [Docs] Add documentation on password salts.
  docs/authentication-and-access-control/password-management.md
Labels: docs

#553 Accept null as graphql query variables
  packages/graphql/src/graphql.controller.spec.ts
  packages/graphql/src/graphql.controller.ts
Labels: feature

#554 Improve createapp CLI by adding options
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/utils/init-git-repo.ts
  packages/cli/src/index.ts
Labels: bug, feature
