Repository FoalTS/foal, pull requests merged in 2019-03, with the labels that each got.

#373 Add 1300 lines of doc comment in the code.
  docs/api-section/public-api-and-cors-requests.md
  docs/authentication-and-access-control/jwt.md
  packages/core/src/auth/login-optional.hook.ts
  packages/core/src/auth/login-required.hook.ts
  packages/core/src/auth/login.hook.ts
  packages/core/src/auth/utils/encrypt-password.util.ts
  packages/core/src/auth/utils/log-in.util.ts
  packages/core/src/auth/utils/log-out.util.ts
  packages/core/src/auth/utils/verify-password.util.ts
  packages/core/src/common/errors/object-does-not-exist.ts
  packages/core/src/common/errors/permission-denied.ts
  packages/core/src/common/errors/validation-error.ts
  packages/core/src/common/hooks/log.hook.ts
  packages/core/src/common/hooks/validate-body.hook.ts
  packages/core/src/common/hooks/validate-headers.hook.ts
  packages/core/src/common/hooks/validate-params.hook.ts
  packages/core/src/common/hooks/validate-query.hook.ts
  packages/core/src/common/utils/controller.util.ts
  packages/core/src/common/utils/escape-prop.ts
  packages/core/src/common/utils/escape.ts
  packages/core/src/common/utils/get-ajv-instance.ts
  packages/core/src/common/utils/is-in-file.util.ts
  packages/core/src/common/utils/render.util.ts
  packages/core/src/common/utils/validate.util.ts
  packages/core/src/core/class.interface.ts
  packages/core/src/core/config.ts
  packages/core/src/core/controllers.ts
  packages/core/src/core/hooks.ts
  packages/core/src/core/http/contexts.ts
  packages/core/src/core/http/http-methods.ts
  packages/core/src/core/http/http-responses.ts
  packages/core/src/core/routes/make-controller-routes.ts
  packages/core/src/core/routes/route.interface.ts
  packages/core/src/core/routes/utils.ts
  packages/core/src/core/service-manager.ts
  packages/core/src/express/create-app.ts
  packages/core/src/express/create-middleware.ts
  packages/core/src/express/handle-errors.ts
  packages/core/src/express/not-found.ts
  packages/ejs/src/index.ts
  packages/jwt/src/jwt-optional.hook.ts
  packages/jwt/src/jwt-required.hook.ts
  packages/jwt/src/jwt.hook.ts
  packages/mongoose/src/utils/fetch-user.util.ts
  packages/password/src/is-common.util.ts
  packages/typeorm/src/entities/group.entity.ts
  packages/typeorm/src/entities/permission.entity.ts
  packages/typeorm/src/entities/user-with-permissions.entity.ts
  packages/typeorm/src/hooks/permission-required.hook.ts
  packages/typeorm/src/utils/fetch-user-with-permissions.util.ts
  packages/typeorm/src/utils/fetch-user.util.ts
Labels: docs

#379 [@foal/cli] Upgrade TSC to version 3 or greater
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
Labels: bug

#391 [@foal/cli] Use source maps during testing
  packages/cli/src/generate/specs/app/src/e2e.ts
  packages/cli/src/generate/specs/app/src/test.ts
  packages/cli/src/generate/templates/app/src/e2e.ts
  packages/cli/src/generate/templates/app/src/test.ts
Labels: enhancement, small

#392 [@foal/cli] Add "foal createsecret" command
  packages/cli/package.json
  packages/cli/src/create-secret/create-secret.spec.ts
  packages/cli/src/create-secret/create-secret.ts
  packages/cli/src/create-secret/index.ts
  packages/cli/src/index.ts
Labels: feature request

#393 Let developers specify a virtual path prefix for static files
  docs/SUMMARY.md
  docs/utilities/static-files.md
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
Labels: feature request

#394 Add a class `ConfigMock` to mock the `Config` when it used as a service
  docs/deployment-and-environments/configuration.md
  packages/core/src/core/config-mock.spec.ts
  packages/core/src/core/config-mock.ts
  packages/core/src/core/index.ts
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
Labels: feature request

#398 Validate cookie
  docs/validation-and-sanitization.md
  packages/core/src/common/hooks/index.ts
  packages/core/src/common/hooks/validate-cookies.hook.ts
  packages/core/src/common/hooks/validate-cookies.spec.ts
Labels: feature request

#396 Add stateless CSRF protection (double submit cookie technique)
  docs/security/csrf-protection.md
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
Labels: feature request
