Repository FoalTS/foal, pull requests merged in 2019-09, with the labels that each got.

#524 fix typo on /6-validation-and-sanitization.md
  docs/tutorials/simple-todo-list/6-validation-and-sanitization.md
Labels: docs

#529 [Docs] Test a hook post function
  docs/architecture/hooks.md
  packages/acceptance-tests/src/examples/architecture/hooks.spec.ts
Labels: docs

#531 [CLI] Set default TS version to 3.5 in new projects (foal createapp)
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
  packages/swagger/src/swagger-controller.ts
Labels: enhancement

#535 [CLI] Prevent infinite loop on main error
  packages/cli/src/generate/specs/app/src/index.mongodb.ts
  packages/cli/src/generate/specs/app/src/index.ts
  packages/cli/src/generate/templates/app/src/index.mongodb.ts
  packages/cli/src/generate/templates/app/src/index.ts
Labels: bug, enhancement

#536 Support post Express middlewares in create-app and support Nuxt.js
  docs/SUMMARY.md
  docs/cookbook/expressjs.md
  docs/frontend-integration/nuxt.js.md
  packages/acceptance-tests/package-lock.json
  packages/acceptance-tests/package.json
  packages/acceptance-tests/src/nuxt.spec.ts
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/redis/src/redis-store.service.spec.ts
  samples/tutorials/nuxt.js/backend/.gitignore
  samples/tutorials/nuxt.js/backend/config/default.json
  samples/tutorials/nuxt.js/backend/config/development.json
  samples/tutorials/nuxt.js/backend/config/e2e.json
  samples/tutorials/nuxt.js/backend/config/production.json
  samples/tutorials/nuxt.js/backend/config/test.json
  samples/tutorials/nuxt.js/backend/ormconfig.js
  samples/tutorials/nuxt.js/backend/package-lock.json
  samples/tutorials/nuxt.js/backend/package.json
  samples/tutorials/nuxt.js/backend/public/index.html
  samples/tutorials/nuxt.js/backend/public/logo.png
  samples/tutorials/nuxt.js/backend/src/app/app.controller.ts
  samples/tutorials/nuxt.js/backend/src/app/controllers/api.controller.spec.ts
  samples/tutorials/nuxt.js/backend/src/app/controllers/api.controller.ts
  samples/tutorials/nuxt.js/backend/src/app/controllers/index.ts
  samples/tutorials/nuxt.js/backend/src/app/entities/index.ts
  samples/tutorials/nuxt.js/backend/src/app/entities/user.entity.ts
  samples/tutorials/nuxt.js/backend/src/app/hooks/index.ts
  samples/tutorials/nuxt.js/backend/src/app/services/index.ts
  samples/tutorials/nuxt.js/backend/src/e2e.ts
  samples/tutorials/nuxt.js/backend/src/e2e/index.ts
  samples/tutorials/nuxt.js/backend/src/index.ts
  samples/tutorials/nuxt.js/backend/src/scripts/create-user.ts
  samples/tutorials/nuxt.js/backend/src/test.ts
  samples/tutorials/nuxt.js/backend/tsconfig.app.json
  samples/tutorials/nuxt.js/backend/tsconfig.e2e.json
  samples/tutorials/nuxt.js/backend/tsconfig.json
  samples/tutorials/nuxt.js/backend/tsconfig.migrations.json
  samples/tutorials/nuxt.js/backend/tsconfig.scripts.json
  samples/tutorials/nuxt.js/backend/tsconfig.test.json
  samples/tutorials/nuxt.js/backend/tslint.json
  samples/tutorials/nuxt.js/frontend/.gitignore
  samples/tutorials/nuxt.js/frontend/README.md
  samples/tutorials/nuxt.js/frontend/assets/README.md
  samples/tutorials/nuxt.js/frontend/components/Logo.vue
  samples/tutorials/nuxt.js/frontend/components/README.md
  samples/tutorials/nuxt.js/frontend/layouts/README.md
  samples/tutorials/nuxt.js/frontend/layouts/default.vue
  samples/tutorials/nuxt.js/frontend/middleware/README.md
  samples/tutorials/nuxt.js/frontend/nuxt.config.js
  samples/tutorials/nuxt.js/frontend/package-lock.json
  samples/tutorials/nuxt.js/frontend/package.json
  samples/tutorials/nuxt.js/frontend/pages/README.md
  samples/tutorials/nuxt.js/frontend/pages/index.vue
  samples/tutorials/nuxt.js/frontend/plugins/README.md
  samples/tutorials/nuxt.js/frontend/static/README.md
  samples/tutorials/nuxt.js/frontend/static/favicon.ico
  samples/tutorials/nuxt.js/frontend/store/README.md
Labels: feature

#515 Add more comparisons to other frameworks
  docs/comparison-with-other-frameworks.md
Labels: docs

#537 Support AJV "nullable" option.
  docs/validation-and-sanitization.md
  packages/core/src/common/utils/get-ajv-instance.spec.ts
  packages/core/src/common/utils/get-ajv-instance.ts
Labels: feature

#544 Support AppController.init to initialize the application
  docs/SUMMARY.md
  docs/cookbook/initialization.md
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/core/src/express/index.ts
Labels: feature

#547 Support ExpressOptions.expressInstance in createApp
  docs/cookbook/expressjs.md
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
Labels: feature

#542 Add TypeStack unserialization and validation hooks
  docs/serializing-and-deserializing.md
  docs/validation-and-sanitization.md
  packages/acceptance-tests/package.json
  packages/acceptance-tests/src/examples/validation-and-sanitization.spec.ts
  packages/acceptance-tests/src/typestack.spec.ts
  packages/typestack/LICENSE
  packages/typestack/README.md
  packages/typestack/package.json
  packages/typestack/src/index.ts
  packages/typestack/src/unserialize-body.hook.spec.ts
  packages/typestack/src/unserialize-body.hook.ts
  packages/typestack/src/validate-body.hook.spec.ts
  packages/typestack/src/validate-body.hook.ts
  packages/typestack/tsconfig-build.json
  packages/typestack/tsconfig.json
  unit_test.sh
Labels: feature
