Repository FoalTS/foal, pull requests merged in 2020-07, with the labels that each got.

#742 [V2][Sessions] Remove the need for a secret
  docs/api/core/classes/_sessions_session_.session.md
  docs/authentication-and-access-control/quick-start.md
  docs/authentication-and-access-control/session-tokens.md
  docs/deployment-and-environments/ship-to-production.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts
  packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts
  packages/acceptance-tests/src/authentication/session-token.token.spec.ts
  packages/acceptance-tests/src/authorization/groups-and-permissions.spec.ts
  packages/acceptance-tests/src/csrf/regular-web-app.stateful.spec.ts
  packages/acceptance-tests/src/csrf/spa-and-api.stateful.spec.ts
  packages/acceptance-tests/src/typeorm.mongodb-store.spec.ts
  packages/acceptance-tests/src/typeorm.redis-store.spec.ts
  packages/core/src/sessions/remove-session-cookie.spec.ts
  packages/core/src/sessions/session.spec.ts
  packages/core/src/sessions/session.ts
  packages/core/src/sessions/set-session-cookie.spec.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/examples/src/scripts/revoke-token.ts
Labels: Breaking change, enhancement

#747 Backers
  README.md
  backers.png
Labels: docs

#746 explainn better when postMiddlewares are executed
  docs/cookbook/expressjs.md
Labels: docs

#760 Update services-and-dependency-injection.md
  docs/architecture/services-and-dependency-injection.md
  packages/acceptance-tests/src/examples/architecture/services-and-dependency-injection.spec.ts
Labels: docs

#755 Extend ValidateBody from typestack
  docs/validation-and-sanitization.md
  packages/typestack/src/validate-body.hook.spec.ts
  packages/typestack/src/validate-body.hook.ts
Labels: feature

#759 Support abstract services & allow to specify the store name in the configuration
  docs/architecture/services-and-dependency-injection.md
  docs/authentication-and-access-control/session-tokens.md
  docs/file-system/local-and-cloud-storage.md
  package-lock.json
  packages/acceptance-tests/src/session.config.spec.ts
  packages/core/src/core/class.interface.ts
  packages/core/src/core/service-manager.spec.ts
  packages/core/src/core/service-manager.ts
  packages/core/src/sessions/index.ts
  packages/core/src/sessions/session-store.spec.ts
  packages/core/src/sessions/session-store.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/internal-test/src/index.ts
  packages/storage/src/abstract-disk.service.spec.ts
  packages/storage/src/abstract-disk.service.ts
  packages/storage/src/disk.service.spec.ts
  packages/storage/src/disk.service.ts
  packages/storage/src/index.ts
  packages/storage/src/local-disk.service.ts
  packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
Labels: feature

#761 Fix some npm and yarn warnings on install
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
Labels: enhancement

#762 [CLI] Catch rejected promises in shell scripts
  packages/cli/src/run-script/run-script.spec.ts
  packages/cli/src/run-script/run-script.ts
Labels: enhancement

#763 Fix typo
  docs/comparison-with-other-frameworks.md
Labels: docs

#764 Add Upload/S3/Swagger sample
  samples/upload-swagger-s3/.eslintrc.js
  samples/upload-swagger-s3/.gitignore
  samples/upload-swagger-s3/README.md
  samples/upload-swagger-s3/config/default.json
  samples/upload-swagger-s3/config/development.json
  samples/upload-swagger-s3/config/e2e.json
  samples/upload-swagger-s3/config/production.json
  samples/upload-swagger-s3/config/test.json
  samples/upload-swagger-s3/images/api.png
  samples/upload-swagger-s3/images/app.png
  samples/upload-swagger-s3/images/aws.png
  samples/upload-swagger-s3/images/bad_email.png
  samples/upload-swagger-s3/images/config.png
  samples/upload-swagger-s3/images/home.png
  samples/upload-swagger-s3/images/missing_profile.png
  samples/upload-swagger-s3/images/no_jwt.png
  samples/upload-swagger-s3/images/swagger.png
  samples/upload-swagger-s3/images/upload.png
  samples/upload-swagger-s3/ormconfig.js
  samples/upload-swagger-s3/package-lock.json
  samples/upload-swagger-s3/package.json
  samples/upload-swagger-s3/public/index.html
  samples/upload-swagger-s3/public/logo.png
  samples/upload-swagger-s3/src/app/app.controller.ts
  samples/upload-swagger-s3/src/app/controllers/api.controller.ts
  samples/upload-swagger-s3/src/app/controllers/index.ts
  samples/upload-swagger-s3/src/app/controllers/openapi.controller.ts
  samples/upload-swagger-s3/src/app/entities/index.ts
  samples/upload-swagger-s3/src/app/entities/user.entity.ts
  samples/upload-swagger-s3/src/app/hooks/index.ts
  samples/upload-swagger-s3/src/app/services/index.ts
  samples/upload-swagger-s3/src/e2e.ts
  samples/upload-swagger-s3/src/e2e/index.ts
  samples/upload-swagger-s3/src/index.ts
  samples/upload-swagger-s3/src/scripts/create-user.ts
  samples/upload-swagger-s3/src/test.ts
  samples/upload-swagger-s3/tsconfig.app.json
  samples/upload-swagger-s3/tsconfig.e2e.json
  samples/upload-swagger-s3/tsconfig.json
  samples/upload-swagger-s3/tsconfig.migrations.json
  samples/upload-swagger-s3/tsconfig.scripts.json
  samples/upload-swagger-s3/tsconfig.test.json
Labels: docs

#767 [V2][Sessions] Do not let TypeORMStore auto-update the database schema.
  docs/authentication-and-access-control/quick-start.md
  docs/authentication-and-access-control/session-tokens.md
  packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts
  packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts
  packages/acceptance-tests/src/authentication/session-token.token.spec.ts
  packages/acceptance-tests/src/authorization/groups-and-permissions.spec.ts
  packages/acceptance-tests/src/csrf/regular-web-app.stateful.spec.ts
  packages/acceptance-tests/src/csrf/spa-and-api.stateful.spec.ts
  packages/typeorm/src/index.ts
  packages/typeorm/src/typeorm-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.ts
Labels: Breaking change, feature

#775 setCsrfCookie import correction
  docs/security/csrf-protection.md
Labels: docs

#774 Update using-another-orm.md
  docs/databases/using-another-orm.md
Labels: docs

#773 Update generate-and-run-migrations.md
  docs/databases/generate-and-run-migrations.md
Labels: docs

#772 Update 6-todos-and-ownership.md
  docs/tutorials/multi-user-todo-list/6-todos-and-ownership.md
Labels: docs

#771 Update 5-auth-controllers-and-hooks.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
Labels: docs

#769 Update 3-the-todo-model.md
  docs/tutorials/simple-todo-list/3-the-todo-model.md
Labels: docs

#780 [V2] Officially support authenticated sessions and allow to perform certain actions on them.
  docs/authentication-and-access-control/session-tokens.md
  packages/core/src/sessions/session-store.spec.ts
  packages/core/src/sessions/session-store.ts
  packages/core/src/sessions/session.spec.ts
  packages/core/src/sessions/session.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/csrf/src/csrf-token-required.hook.spec.ts
  packages/csrf/src/get-csrf-token.util.spec.ts
  packages/mongodb/package.json
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
  packages/redis/package.json
  packages/redis/src/redis-store.service.spec.ts
  packages/redis/src/redis-store.service.ts
  packages/typeorm/src/typeorm-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.ts
Labels: Breaking change, feature

#781 [V2] Support flash sessions
  docs/authentication-and-access-control/session-tokens.md
  packages/acceptance-tests/package.json
  packages/acceptance-tests/src/authentication/session-token.flash.spec.ts
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/sessions/index.ts
  packages/core/src/sessions/session-state.interface.ts
  packages/core/src/sessions/session-store.spec.ts
  packages/core/src/sessions/session.spec.ts
  packages/core/src/sessions/session.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/csrf/package.json
  packages/csrf/src/csrf-token-required.hook.spec.ts
  packages/csrf/src/get-csrf-token.util.spec.ts
  packages/ejs/package.json
  packages/formidable/package.json
  packages/graphql/package.json
  packages/jwks-rsa/package.json
  packages/jwt/package.json
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
  packages/password/package.json
  packages/redis/src/redis-store.service.spec.ts
  packages/redis/src/redis-store.service.ts
  packages/social/package.json
  packages/storage/package.json
  packages/swagger/package.json
  packages/typeorm/package.json
  packages/typeorm/src/typeorm-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.ts
  packages/typestack/package.json
Labels: Breaking change, feature
