Repository FoalTS/foal, pull requests merged in 2020-04, with the labels that each got.

#651 [@foal/storage] Add hook @ValidateMultipartFormDataBody (file uploads)
  docs/file-system/local-and-cloud-storage.md
  docs/file-system/upload-and-download-files.md
  packages/aws-s3/src/s3-disk.service.ts
  packages/cli/src/generate/specs/app/.eslintrc.js
  packages/cli/src/generate/templates/app/.eslintrc.js
  packages/core/src/common/tokens/generate-token.util.ts
  packages/core/src/common/utils/render.util.ts
  packages/core/src/core/http/http-responses.ts
  packages/core/src/express/send-response.ts
  packages/core/src/openapi/create-open-api-document.ts
  packages/core/src/openapi/metadata-getters/get-api-complete-operation.ts
  packages/core/src/openapi/metadata-getters/get-api-components.ts
  packages/examples/.gitignore
  packages/examples/config/default.yml
  packages/examples/package.json
  packages/examples/src/app/app.controller.ts
  packages/examples/src/app/controllers/index.ts
  packages/examples/src/app/controllers/openapi.controller.ts
  packages/examples/src/app/controllers/profile.controller.ts
  packages/examples/src/app/entities/user.entity.ts
  packages/examples/src/migrations/1585904937181-add-profile.ts
  packages/examples/templates/profile.html
  packages/social/src/abstract-provider.service.ts
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/storage/src/abstract-disk.service.ts
  packages/storage/src/disk.service.ts
  packages/storage/src/image.test.png
  packages/storage/src/image.test2.png
  packages/storage/src/index.ts
  packages/storage/src/local-disk.service.ts
  packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
  tslint.json
Labels: feature

#672 v1.7.1
  lerna.json
  packages/acceptance-tests/package-lock.json
  packages/acceptance-tests/package.json
  packages/aws-s3/package-lock.json
  packages/aws-s3/package.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/csrf/package-lock.json
  packages/csrf/package.json
  packages/ejs/package-lock.json
  packages/ejs/package.json
  packages/examples/package-lock.json
  packages/examples/package.json
  packages/formidable/package-lock.json
  packages/formidable/package.json
  packages/graphql/package-lock.json
  packages/graphql/package.json
  packages/internal-test/package-lock.json
  packages/internal-test/package.json
  packages/jwks-rsa/package-lock.json
  packages/jwks-rsa/package.json
  packages/jwt/package-lock.json
  packages/jwt/package.json
  packages/mongodb/package-lock.json
  packages/mongodb/package.json
  packages/mongoose/package-lock.json
  packages/mongoose/package.json
  packages/password/package-lock.json
  packages/password/package.json
  packages/redis/package-lock.json
  packages/redis/package.json
  packages/social/package-lock.json
  packages/social/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
  packages/swagger/package-lock.json
  packages/swagger/package.json
  packages/typeorm/package-lock.json
  packages/typeorm/package.json
  packages/typestack/package-lock.json
  packages/typestack/package.json
Labels: bug

#675 [Dependency injection] Support interface and generic classes injection
  docs/architecture/services-and-dependency-injection.md
  packages/acceptance-tests/src/examples/architecture/services-and-dependency-injection.spec.ts
  packages/core/src/core/index.ts
  packages/core/src/core/service-manager.spec.ts
  packages/core/src/core/service-manager.ts
Labels: feature

#677 Support other character encodings for JWT secrets
  docs/authentication-and-access-control/jwt.md
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
Labels: feature

#679 Fix typo in services-and-dependency-injection.md
  docs/architecture/services-and-dependency-injection.md
Labels: docs

#680 Fix a broken link
  docs/databases/typeorm.md
  docs/file-system/local-and-cloud-storage.md
Labels: docs

#682 UserWithPermissions extends BaseEntity and new UserWithPermissions.withPerm static method
  .github/workflows/test.yml
  docker-compose.yml
  docs/authentication-and-access-control/groups-and-permissions.md
  packages/typeorm/src/entities/group.entity.spec.ts
  packages/typeorm/src/entities/group.entity.ts
  packages/typeorm/src/entities/permission.entity.spec.ts
  packages/typeorm/src/entities/permission.entity.ts
  packages/typeorm/src/entities/user-with-permissions.entity.spec.ts
  packages/typeorm/src/entities/user-with-permissions.entity.ts
Labels: feature

#678 Support service initialization (boot method)
  docs/SUMMARY.md
  docs/architecture/initialization.md
  packages/core/src/core/service-manager.spec.ts
  packages/core/src/core/service-manager.ts
Labels: feature

#685 Fix @types/express types problems
  e2e_test.sh
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/core/http/contexts.ts
  packages/core/src/core/http/mime.d.ts
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/core/src/express/create-middleware.spec.ts
  packages/core/src/express/create-middleware.ts
  packages/core/src/express/express.d.ts
  packages/core/src/express/handle-errors.ts
  packages/core/src/express/not-found.ts
  packages/core/src/express/send-response.ts
Labels: bug, enhancement
