Repository FoalTS/foal, pull requests merged in 2020-05, with the labels that each got.

#688 Remove mongoose types
  packages/cli/src/generate/generators/model/create-model.spec.ts
  packages/cli/src/generate/generators/model/create-model.ts
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/src/app/models/index.ts
  packages/cli/src/generate/specs/app/src/app/models/user.model.ts
  packages/cli/src/generate/specs/model/index.sorted.ts
  packages/cli/src/generate/specs/model/index.ts
  packages/cli/src/generate/specs/model/test-foo-bar.model.ts
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/src/app/models/index.ts
  packages/cli/src/generate/templates/app/src/app/models/user.model.ts
  packages/cli/src/generate/templates/model/model.ts
  packages/mongodb/package-lock.json
  packages/mongodb/package.json
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
  packages/mongodb/src/mongodb.d.ts
  packages/mongoose/package-lock.json
  packages/mongoose/package.json
  packages/mongoose/src/utils/fetch-user.util.spec.ts
  packages/mongoose/src/utils/fetch-user.util.ts
  packages/mongoose/src/utils/mongoose.d.ts
Labels: bug

#690 Fix Express types
  docs/tutorials/mongodb-todo-list/3-the-todo-model.md
  packages/acceptance-tests/src/error-handling.spec.ts
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/core/http/contexts.ts
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/core/src/express/create-middleware.spec.ts
  packages/core/src/express/create-middleware.ts
  packages/core/src/express/express.d.ts
  packages/core/src/express/handle-errors.spec.ts
  packages/core/src/express/handle-errors.ts
  packages/core/src/express/not-found.ts
  packages/core/src/express/send-response.spec.ts
  packages/core/src/express/send-response.ts
  packages/core/src/sessions/token.hook.ts
  packages/formidable/package-lock.json
  packages/formidable/package.json
  packages/formidable/src/parse-form.spec.ts
  packages/formidable/src/parse-form.ts
  packages/jwt/src/jwt.hook.ts
Labels: bug

#692 Docs: wording, spelling and punctuation fixes
  docs/tutorials/simple-todo-list/3-the-todo-model.md
Labels: docs

#691 Minor grammatical fixes in 2-introduction.md
  docs/tutorials/simple-todo-list/2-introduction.md
Labels: docs

#684 [V2] Simplify commands for scripts, migrations and improve coder experience
  docs/api-section/graphql.md
  docs/api-section/openapi-and-swagger-ui.md
  docs/authentication-and-access-control/groups-and-permissions.md
  docs/authentication-and-access-control/session-tokens.md
  docs/authentication-and-access-control/user-class.md
  docs/cloud/aws-beanstalk.md
  docs/cloud/firebase.md
  docs/cookbook/scheduling-jobs.md
  docs/databases/generate-and-run-migrations.md
  docs/deployment-and-environments/ship-to-production.md
  docs/development-environment/build-and-start-the-app.md
  docs/development-environment/create-and-run-scripts.md
  docs/tutorials/mongodb-todo-list/4-the-shell-script-create-todo.md
  docs/tutorials/multi-user-todo-list/2-the-user-and-todo-models.md
  docs/tutorials/multi-user-todo-list/3-the-shell-scripts.md
  docs/tutorials/simple-todo-list/3-the-todo-model.md
  docs/tutorials/simple-todo-list/4-the-shell-script-create-todo.md
  e2e_test.sh
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/specs/app/tsconfig.app.json
  packages/cli/src/generate/specs/app/tsconfig.migrations.json
  packages/cli/src/generate/specs/app/tsconfig.scripts.json
  packages/cli/src/generate/specs/vscode-config/tasks.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
  packages/cli/src/generate/templates/app/tsconfig.app.json
  packages/cli/src/generate/templates/app/tsconfig.migrations.json
  packages/cli/src/generate/templates/app/tsconfig.scripts.json
  packages/cli/src/generate/templates/vscode-config/tasks.json
  packages/cli/src/run-script/run-script.spec.ts
  packages/cli/src/run-script/run-script.ts
  packages/examples/package.json
Labels: Breaking change, enhancement

#697 Update angular-react-vue.md
  docs/frontend-integration/angular-react-vue.md
Labels: docs

#698 Fix v1.8 docs
  docs/architecture/services-and-dependency-injection.md
  docs/authentication-and-access-control/groups-and-permissions.md
Labels: docs

#696 [CONTRIBUTING] Add dependency, testing & version policies and improve on-boarding
  .github/CONTRIBUTING.MD
Labels: docs

#699 [V2] Drop NodeJS 8 support and test NodeJS 12.
  .github/workflows/daily-test.yml
  .github/workflows/test.yml
  README.md
  docs/README.md
  docs/cloud/firebase.md
  docs/tutorials/mongodb-todo-list/1-installation.md
  docs/tutorials/simple-todo-list/1-installation.md
  packages/aws-s3/README.md
  packages/aws-s3/package.json
  packages/aws-s3/src/s3-disk.service.spec.ts
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/templates/app/package.json
  packages/core/README.md
  packages/core/package.json
  packages/core/src/common/utils/render-error.util.spec.ts
  packages/core/src/index.ts
  packages/csrf/README.md
  packages/csrf/package.json
  packages/ejs/README.md
  packages/ejs/package.json
  packages/examples/package.json
  packages/formidable/README.md
  packages/formidable/package.json
  packages/graphql/README.md
  packages/graphql/package.json
  packages/internal-test/package.json
  packages/jwks-rsa/README.md
  packages/jwks-rsa/package.json
  packages/jwt/README.md
  packages/jwt/package.json
  packages/mongodb/README.md
  packages/mongodb/package.json
  packages/mongoose/README.md
  packages/mongoose/package.json
  packages/password/README.md
  packages/password/package.json
  packages/redis/README.md
  packages/redis/package.json
  packages/social/README.md
  packages/social/package.json
  packages/storage/README.md
  packages/storage/package.json
  packages/storage/src/disk.service.spec.ts
  packages/swagger/README.md
  packages/swagger/package.json
  packages/typeorm/README.md
  packages/typeorm/package.json
  packages/typestack/README.md
  packages/typestack/package.json
Labels: enhancement

#701 Make JWTRequired and TokenRequired work with TypeORM and MongoDB
  docs/SUMMARY.md
  docs/databases/mongodb.md
  docs/databases/using-mongoose.md
  package-lock.json
  packages/acceptance-tests/src/typeorm.mongodb-store.spec.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/mongoose/src/utils/fetch-user.util.spec.ts
  packages/mongoose/src/utils/fetch-user.util.ts
  packages/typeorm/package-lock.json
  packages/typeorm/package.json
  packages/typeorm/src/utils/fetch-mongodb-user.util.spec.ts
  packages/typeorm/src/utils/fetch-mongodb-user.util.ts
  packages/typeorm/src/utils/index.ts
Labels: feature

#703 Make all frontend `connect` projects build on unix
  packages/cli/src/generate/generators/angular/connect-angular.ts
  packages/cli/src/generate/generators/vue/connect-vue.ts
Labels: bug, enhancement

#705 Pass request body and path parameters as third and second arguments to the controller methods
  docs/architecture/controllers.md
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
  packages/core/src/express/create-middleware.spec.ts
  packages/core/src/express/create-middleware.ts
  packages/core/src/sessions/session.ts
Labels: feature

#707 Any command failure ends shell script execution
  benchmarks/run.sh
  e2e_test.sh
  unit_test.sh
Labels: enhancement, internal

#709 Add HttpResponseTooManyRequests and isHttpResponseTooManyRequests
  .github/CONTRIBUTING.MD
  benchmarks/run.sh
  e2e_test.sh
  packages/core/src/core/http/http-responses.spec.ts
  packages/core/src/core/http/http-responses.ts
  unit_test.sh
Labels: feature

#712 [CLI] Refactor the code of the generators to make it more maintainable and understandable
  packages/cli/package.json
  packages/cli/src/generate/file-system.spec.ts
  packages/cli/src/generate/file-system.ts
  packages/cli/src/generate/generators/angular/connect-angular.spec.ts
  packages/cli/src/generate/generators/angular/connect-angular.ts
  packages/cli/src/generate/generators/app/create-app.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/generators/controller/create-controller.spec.ts
  packages/cli/src/generate/generators/controller/create-controller.ts
  packages/cli/src/generate/generators/controller/index.ts
  packages/cli/src/generate/generators/entity/create-entity.spec.ts
  packages/cli/src/generate/generators/entity/create-entity.ts
  packages/cli/src/generate/generators/hook/create-hook.spec.ts
  packages/cli/src/generate/generators/hook/create-hook.ts
  packages/cli/src/generate/generators/model/create-model.spec.ts
  packages/cli/src/generate/generators/model/create-model.ts
  packages/cli/src/generate/generators/react/connect-react.spec.ts
  packages/cli/src/generate/generators/react/connect-react.ts
  packages/cli/src/generate/generators/rest-api/create-rest-api.spec.ts
  packages/cli/src/generate/generators/rest-api/create-rest-api.ts
  packages/cli/src/generate/generators/script/create-script.spec.ts
  packages/cli/src/generate/generators/script/create-script.ts
  packages/cli/src/generate/generators/service/create-service.spec.ts
  packages/cli/src/generate/generators/service/create-service.ts
  packages/cli/src/generate/generators/sub-app/create-sub-app.spec.ts
  packages/cli/src/generate/generators/sub-app/create-sub-app.ts
  packages/cli/src/generate/generators/vscode-config/create-vscode-config.spec.ts
  packages/cli/src/generate/generators/vscode-config/create-vscode-config.ts
  packages/cli/src/generate/generators/vue/connect-vue.spec.ts
  packages/cli/src/generate/generators/vue/connect-vue.ts
  packages/cli/src/generate/specs/controller/test-foo-bar.controller.graphql.ts
  packages/cli/src/generate/specs/controller/test-foo-bar.controller.login.ts
  packages/cli/src/generate/specs/controller/test-foo-bar.controller.rest.ts
  packages/cli/src/generate/templates/controller/controller.graphql.ts
  packages/cli/src/generate/templates/controller/controller.login.ts
  packages/cli/src/generate/templates/controller/controller.rest.ts
  packages/cli/src/generate/utils/generator.ts
  packages/cli/src/generate/utils/index.ts
  packages/cli/src/generate/utils/test-environment.ts
  packages/cli/src/index.ts
  packages/cli/src/run-script/run-script.spec.ts
  packages/cli/src/test.ts
Labels: internal

#719 fix broken docs link
  README.md
  packages/aws-s3/README.md
  packages/cli/README.md
  packages/core/README.md
  packages/csrf/README.md
  packages/ejs/README.md
  packages/formidable/README.md
  packages/graphql/README.md
  packages/jwks-rsa/README.md
  packages/jwt/README.md
  packages/mongodb/README.md
  packages/mongoose/README.md
  packages/password/README.md
  packages/redis/README.md
  packages/social/README.md
  packages/storage/README.md
  packages/swagger/README.md
  packages/typeorm/README.md
  packages/typestack/README.md
Labels: docs

#717 Support custom type for ctx.state
  packages/core/src/core/http/contexts.ts
Labels: feature

#721 Fix linter errors in tutorial shell scripts
  docs/tutorials/multi-user-todo-list/3-the-shell-scripts.md
Labels: docs

#722 fix http-responses typo mistakes
  packages/acceptance-tests/src/upload-and-download.spec.ts
  packages/acceptance-tests/src/upload-and-download.typeorm.spec.ts
  packages/core/src/core/http/http-responses.spec.ts
  packages/core/src/core/http/http-responses.ts
  packages/storage/src/abstract-disk.service.spec.ts
  packages/storage/src/abstract-disk.service.ts
Labels: bug, enhancement

#723 Remove Auth0 (and Cognito) tests
  .github/workflows/test.yml
  packages/acceptance-tests/src/authentication/jwt.jwks.spec.ts
Labels: internal

#729 [Sessions] Allow to specify the store name in a configuration file
  docs/authentication-and-access-control/session-tokens.md
  packages/core/package.json
  packages/core/src/sessions/token-optional.hook.ts
  packages/core/src/sessions/token-required.hook.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/internal-test/src/index.ts
  packages/mongodb/src/index.ts
  packages/redis/src/index.ts
  packages/storage/src/disk.service.spec.ts
  packages/storage/src/disk.service.ts
  packages/typeorm/src/index.ts
Labels: feature

#732 [V2] Replace Config.get with Config.get2
  docs/api-section/graphql.md
  docs/authentication-and-access-control/jwt.md
  docs/authentication-and-access-control/quick-start.md
  docs/cloud/aws-beanstalk.md
  docs/cookbook/limit-repeated-requests.md
  docs/databases/mongodb.md
  docs/databases/typeorm.md
  docs/deployment-and-environments/configuration.md
  docs/frontend-integration/nuxt.js.md
  packages/acceptance-tests/src/authentication/jwt.cookie.spec.ts
  packages/acceptance-tests/src/examples/cookbook/limit-repeated-requests.spec.ts
  packages/aws-s3/src/s3-disk.service.spec.ts
  packages/aws-s3/src/s3-disk.service.ts
  packages/cli/src/generate/specs/app/ormconfig.js
  packages/cli/src/generate/specs/app/src/index.mongodb.ts
  packages/cli/src/generate/specs/app/src/index.ts
  packages/cli/src/generate/templates/app/ormconfig.js
  packages/cli/src/generate/templates/app/src/index.mongodb.ts
  packages/cli/src/generate/templates/app/src/index.ts
  packages/core/src/common/hooks/validate-body.hook.ts
  packages/core/src/common/hooks/validate-cookie.hook.ts
  packages/core/src/common/hooks/validate-cookies.hook.ts
  packages/core/src/common/hooks/validate-header.hook.ts
  packages/core/src/common/hooks/validate-headers.hook.ts
  packages/core/src/common/hooks/validate-params.hook.ts
  packages/core/src/common/hooks/validate-path-param.hook.ts
  packages/core/src/common/hooks/validate-query-param.hook.ts
  packages/core/src/common/hooks/validate-query.hook.ts
  packages/core/src/common/utils/get-ajv-instance.ts
  packages/core/src/common/utils/render-error.util.ts
  packages/core/src/common/utils/render.util.ts
  packages/core/src/core/config/config-mock.spec.ts
  packages/core/src/core/config/config-mock.ts
  packages/core/src/core/config/config.spec.ts
  packages/core/src/core/config/config.ts
  packages/core/src/core/config/index.ts
  packages/core/src/express/create-app.ts
  packages/core/src/express/handle-errors.ts
  packages/core/src/sessions/remove-session-cookie.ts
  packages/core/src/sessions/session-store.ts
  packages/core/src/sessions/set-session-cookie.ts
  packages/core/src/sessions/token-optional.hook.ts
  packages/core/src/sessions/token-required.hook.ts
  packages/core/src/sessions/token.hook.ts
  packages/csrf/src/csrf-token-required.hook.ts
  packages/csrf/src/get-csrf-token.util.ts
  packages/csrf/src/set-csrf-cookie.ts
  packages/examples/src/index.ts
  packages/graphql/src/mask-and-log-error.ts
  packages/jwt/src/jwt-optional.hook.ts
  packages/jwt/src/jwt-required.hook.ts
  packages/jwt/src/jwt.hook.ts
  packages/redis/src/redis-store.service.ts
  packages/social/src/abstract-provider.service.spec.ts
  packages/social/src/abstract-provider.service.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
Labels: Breaking change, enhancement

#730 [V2] [File upload] Access file size, mime type, encoding and original file name
  docs/file-system/local-and-cloud-storage.md
  docs/file-system/upload-and-download-files.md
  packages/aws-s3/src/s3-disk.service.spec.ts
  packages/aws-s3/src/s3-disk.service.ts
  packages/internal-test/src/index.ts
  packages/storage/src/abstract-disk.service.spec.ts
  packages/storage/src/abstract-disk.service.ts
  packages/storage/src/disk.service.spec.ts
  packages/storage/src/disk.service.ts
  packages/storage/src/file.spec.ts
  packages/storage/src/file.ts
  packages/storage/src/index.ts
  packages/storage/src/local-disk.service.spec.ts
  packages/storage/src/local-disk.service.ts
  packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
Labels: Breaking change, feature

#733 [V2] Initialize services by default
  docs/architecture/initialization.md
  e2e_test.sh
  packages/acceptance-tests/src/mongoose-db.mongodb-store.spec.ts
  packages/acceptance-tests/src/mongoose-db.redis-store.spec.ts
  packages/acceptance-tests/src/typeorm.mongodb-store.spec.ts
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
  packages/redis/src/redis-store.service.spec.ts
  packages/redis/src/redis-store.service.ts
Labels: feature
