Repository FoalTS/foal, pull requests merged in 2020-08, with the labels that each got.

#786 Fix typestack validateBody hook
  packages/typestack/src/validate-body.hook.spec.ts
  packages/typestack/src/validate-body.hook.ts
Labels: bug

#790 [Groups & Perms] Make cmd work on all OS
  docs/authentication-and-access-control/groups-and-permissions.md
Labels: docs

#792 [V2] Simplify session system, make it more robust and add new features
  docs/authentication-and-access-control/quick-start.md
  docs/authentication-and-access-control/session-tokens.md
  docs/authentication-and-access-control/social-auth.md
  docs/databases/typeorm.md
  docs/security/csrf-protection.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  docs/tutorials/multi-user-todo-list/7-the-signup-page.md
  packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts
  packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts
  packages/acceptance-tests/src/authentication/session-token.flash.spec.ts
  packages/acceptance-tests/src/authentication/session-token.token.spec.ts
  packages/acceptance-tests/src/authorization/groups-and-permissions.spec.ts
  packages/acceptance-tests/src/csrf/regular-web-app.stateful.spec.ts
  packages/acceptance-tests/src/csrf/spa-and-api.stateful.spec.ts
  packages/acceptance-tests/src/session.config.spec.ts
  packages/acceptance-tests/src/typeorm.mongodb-store.spec.ts
  packages/acceptance-tests/src/typeorm.redis-store.spec.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/core/src/sessions/constants.ts
  packages/core/src/sessions/create-session.spec.ts
  packages/core/src/sessions/create-session.ts
  packages/core/src/sessions/index.ts
  packages/core/src/sessions/read-session.spec.ts
  packages/core/src/sessions/read-session.ts
  packages/core/src/sessions/session-state.interface.ts
  packages/core/src/sessions/session-store.spec.ts
  packages/core/src/sessions/session-store.ts
  packages/core/src/sessions/session.spec.ts
  packages/core/src/sessions/session.ts
  packages/core/src/sessions/set-session-cookie.spec.ts
  packages/core/src/sessions/set-session-cookie.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/csrf/src/csrf-token-required.hook.spec.ts
  packages/csrf/src/get-csrf-token.util.spec.ts
  packages/examples/src/app/controllers/auth.controller.ts
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
  packages/redis/src/redis-store.service.spec.ts
  packages/redis/src/redis-store.service.ts
  packages/typeorm/src/typeorm-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.ts
Labels: Breaking change, enhancement, feature

#800 [MongoStore] Use sessionID instead of _id
  docs/authentication-and-access-control/session-tokens.md
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
Labels: enhancement, internal

#801 [V2][Sessions] Remove the need of setSessionCookie in login
  docs/authentication-and-access-control/quick-start.md
  docs/authentication-and-access-control/social-auth.md
  docs/security/csrf-protection.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  docs/tutorials/multi-user-todo-list/7-the-signup-page.md
  packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts
  packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts
  packages/acceptance-tests/src/csrf/regular-web-app.stateful.spec.ts
  packages/acceptance-tests/src/csrf/spa-and-api.stateful.spec.ts
  packages/core/src/sessions/create-session.spec.ts
  packages/core/src/sessions/read-session.spec.ts
  packages/core/src/sessions/session.spec.ts
  packages/core/src/sessions/session.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/typeorm/src/typeorm-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.ts
Labels: feature
