Repository FoalTS/foal, pull requests merged in 2020-03, with the labels that each got.

#657 Expose isFileDoesNotExist and improve CI tests
  .github/workflows/test.yml
  docs/file-system/local-and-cloud-storage.md
  packages/storage/src/index.ts
Labels: feature, internal

#661 Update quick-start.md
  docs/authentication-and-access-control/quick-start.md
Labels: docs

#662 [v1.7.0] Upgrade dependencies
  packages/aws-s3/package-lock.json
  packages/aws-s3/package.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/jwks-rsa/package-lock.json
  packages/jwks-rsa/package.json
Labels: enhancement, internal

#659 [V2] [Sessions] Simplify logout
  docs/authentication-and-access-control/quick-start.md
  docs/authentication-and-access-control/session-tokens.md
  docs/tutorials/multi-user-todo-list/5-auth-controllers-and-hooks.md
  packages/acceptance-tests/src/authentication/session-token.cookie.redirection.spec.ts
  packages/acceptance-tests/src/authentication/session-token.cookie.spec.ts
  packages/acceptance-tests/src/authentication/session-token.token.spec.ts
  packages/acceptance-tests/src/mongoose-db.mongodb-store.spec.ts
  packages/acceptance-tests/src/mongoose-db.redis-store.spec.ts
  packages/core/src/sessions/session-store.spec.ts
  packages/core/src/sessions/session.spec.ts
  packages/core/src/sessions/session.ts
  packages/core/src/sessions/token.hook.spec.ts
  packages/core/src/sessions/token.hook.ts
  packages/csrf/src/csrf-token-required.hook.spec.ts
  packages/csrf/src/get-csrf-token.util.spec.ts
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/mongodb/src/mongodb-store.service.ts
  packages/redis/src/redis-store.service.spec.ts
  packages/redis/src/redis-store.service.ts
  packages/typeorm/src/typeorm-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.ts
Labels: Breaking change, enhancement
