Repository FoalTS/foal, pull requests merged in 2020-01, with the labels that each got.

#605 Fix typo
  docs/comparison-with-other-frameworks.md
Labels: docs

#608 [GraphQL] Make TypeGraphQL a dev dep
  packages/graphql/package.json
Labels: bug, enhancement

#609 [@foal/mongodb] Upgrade MongoDB to v3.4.1
  packages/acceptance-tests/package-lock.json
  packages/mongodb/package-lock.json
  packages/mongodb/package.json
Labels: enhancement

#610 [CLI] Remove wrong npm naming control
  packages/cli/src/generate/generators/app/create-app.ts
Labels: enhancement

#617 Docs: groups-and-permissions.md add to example
  docs/authentication-and-access-control/groups-and-permissions.md
Labels: docs

#621 Clean the build directory before building the app
  e2e_test.sh
  packages/cli/package.json
  packages/cli/src/generate/generators/sub-app/create-sub-app.spec.ts
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
  packages/cli/src/generate/utils/index.ts
  packages/cli/src/index.ts
  packages/cli/src/rmdir/index.ts
  packages/cli/src/rmdir/rmdir.util.spec.ts
  packages/cli/src/rmdir/rmdir.util.ts
Labels: feature

#613 [v1.6.0] Upgrade external dependencies
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/graphql/package-lock.json
  packages/graphql/package.json
  packages/mongodb/package-lock.json
  packages/mongodb/package.json
  packages/swagger/package-lock.json
  packages/swagger/package.json
Labels: enhancement

#623 Update graphql.md
  docs/api-section/graphql.md
Labels: docs

#624 Upgrade graphql and modify tsconfig
  packages/graphql/package-lock.json
  packages/graphql/package.json
  packages/graphql/tsconfig.json
Labels: internal

#599 feat(Core/createApp): Augment `createApp` to allow optionally passing ServiceManager object
  docs/architecture/services-and-dependency-injection.md
  packages/acceptance-tests/src/examples/architecture/services-and-dependency-injection.spec.ts
  packages/core/src/express/create-app.spec.ts
  packages/core/src/express/create-app.ts
Labels: feature
