Repository FoalTS/foal, pull requests merged in 2021-05, with the labels that each got.

#923 AJV $data support #920
  docs/docs/common/validation-and-sanitization.md
  packages/core/src/common/utils/get-ajv-instance.spec.ts
  packages/core/src/common/utils/get-ajv-instance.ts
Labels: feature

#926 [Docs] Add note on the dotenv library
  docs/docs/architecture/configuration.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/architecture/configuration.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/architecture/configuration.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/architecture/configuration.md
Labels: docs

#927 [CLI] Simplify default create-user script
  docs/docs/authentication-and-access-control/groups-and-permissions.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/authentication-and-access-control/groups-and-permissions.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication-and-access-control/groups-and-permissions.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/authentication-and-access-control/groups-and-permissions.md
  packages/cli/src/generate/specs/app/src/scripts/create-user.ts
  packages/cli/src/generate/templates/app/src/scripts/create-user.ts
Labels: enhancement

#928 Update current.json
  docs/i18n/id/docusaurus-plugin-content-docs/current.json
Labels: docs

#931 Fix renderError error
  packages/core/src/common/utils/render-error.util.spec.ts
  packages/core/src/common/utils/render-error.util.ts
Labels: bug

#933 Fix typo in architecture docs code example
  docs/docs/architecture/services-and-dependency-injection.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/architecture/services-and-dependency-injection.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/architecture/services-and-dependency-injection.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/architecture/services-and-dependency-injection.md
Labels: docs

#936 Fix typo in openapi docs
  docs/docs/api-section/openapi-and-swagger-ui.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
Labels: docs

#935 fix typo in upgrade to v2 openapi docs
  docs/docs/upgrade-to-v2/openapi.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/upgrade-to-v2/openapi.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/upgrade-to-v2/openapi.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/upgrade-to-v2/openapi.md
Labels: docs

#938 Add cache option to Disk.createHttpResponse
  docs/docs/file-system/upload-and-download-files.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md
  packages/storage/src/disk.service.spec.ts
  packages/storage/src/disk.service.ts
Labels: feature

#942 Be able to read file size after `ValidateMultipartFormDataBody`.
  docs/blog/assets/version-2.5-is-here/banner.png
  docs/blog/version-2.5-release-notes.md
  docs/docs/file-system/upload-and-download-files.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/file-system/upload-and-download-files.md
  docs/static/blog/twitter-banners/version-2.5-release-notes.png
  packages/storage/src/file.spec.ts
  packages/storage/src/file.ts
  packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
Labels: feature

#947 [CLI] Make the "npm run develop" command watch config files
  docs/blog/version-2.5-release-notes.md
  docs/docs/api-section/gRPC.md
  docs/docs/api-section/graphql.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/gRPC.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/graphql.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/gRPC.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/graphql.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/api-section/gRPC.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/api-section/graphql.md
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
Labels: enhancement

#950 createOpenApiDocument accepts an optional serviceManager
  docs/blog/version-2.5-release-notes.md
  docs/docs/api-section/openapi-and-swagger-ui.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/api-section/openapi-and-swagger-ui.md
  packages/core/src/core/openapi/create-open-api-document.spec.ts
  packages/core/src/core/openapi/create-open-api-document.ts
Labels: feature

#953 [Docs] Remove v1 end-of-life warnings
  docs/docs/README.md
  docs/docusaurus.config.js
  docs/i18n/es/docusaurus-plugin-content-docs/current/README.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/README.md
  docs/i18n/id/docusaurus-plugin-content-docs/current/README.md
  docs/src/theme/DocVersionSuggestions/index.js
Labels: docs
