Repository FoalTS/foal, pull requests merged in 2022-11, with the labels that each got.

#1164 Add v3 release notes
  docs/blog/2021-02-03-version-2.1-release-notes.md
  docs/blog/2021-02-17-whats-new-in-version-2-part-1.md
  docs/blog/2021-02-25-version-2.2-release-notes.md
  docs/blog/2021-03-02-whats-new-in-version-2-part-2.md
  docs/blog/2021-03-11-whats-new-in-version-2-part-3.md
  docs/blog/2021-04-08-whats-new-in-version-2-part-4.md
  docs/blog/2021-04-22-version-2.3-release-notes.md
  docs/blog/2021-05-19-version-2.4-release-notes.md
  docs/blog/2021-06-11-version-2.5-release-notes.md
  docs/blog/2021-09-19-version-2.6-release-notes.md
  docs/blog/2021-12-12-version-2.7-release-notes.md
  docs/blog/2022-02-13-version-2.8-release-notes.md
  docs/blog/2022-05-29-version-2.9-release-notes.md
  docs/blog/2022-06-13-FoalTS-2022-survey-is-open.md
  docs/blog/2022-08-11-version-2.10-release-notes.md
  docs/blog/2022-10-09-version-2.11-release-notes.md
  docs/blog/2022-11-01-version-3.0-release-notes.md
  docs/blog/assets/version-3.0-is-here/banner.png
  docs/docs/upgrade-to-v3/README.md
  docs/static/blog/twitter-banners/version-3.0-release-notes.png
Labels: docs / website

#1178 Adapt generated eslint config to support ctx.session!
  packages/cli/src/generate/specs/app/.eslintrc.js
  packages/cli/src/generate/templates/app/.eslintrc.js
Labels: enhancement

#1177 Remove pm2 to fix CLI failure
  .github/workflows/daily-test.yml
  .github/workflows/test.yml
  e2e_test.sh
Labels: internal

#1181 Add "plus button" in sponsor section on the landing page
  docs/src/pages/index.jsx
Labels: docs / blog / website

#1184 docs(minor) Change reference to Ajv version (6 -> 8)
  docs/docs/common/validation-and-sanitization.md
Labels: docs / blog / website

#1185 Support whitespaces around variable names in `.env` files
  packages/core/src/core/config/env.spec.ts
  packages/core/src/core/config/env.ts
Labels: bug

#1186 [CLI] Add internal `setOrUpdateProjectDependency` methods to support future `foal upgrade` command
  packages/cli/src/generate/file-system.spec.ts
  packages/cli/src/generate/file-system.ts
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
Labels: internal

#1187 Support custom cookie domain in social auth
  docs/blog/assets/version-3.1-is-here/banner.png
  docs/blog/version-3.1-release-notes.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/authentication-and-access-control/social-auth.md
  docs/static/blog/twitter-banners/version-3.1-release-notes.png
  packages/social/src/abstract-provider.service.spec.ts
  packages/social/src/abstract-provider.service.ts
Labels: feature

#1191 Changke is using foal
  docs/src/pages/who-is-using-foal.jsx
  docs/static/img/who-is-using-foal/blog.sinzy.net.png
Labels: docs / blog / website

#1193 [CLI] Add `foal upgrade [version]` command
  docs/blog/version-3.1-release-notes.md
  docs/docs/cli/commands.md
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/generate/fixtures/upgrade/package.json
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/generators/index.ts
  packages/cli/src/generate/generators/upgrade/index.ts
  packages/cli/src/generate/generators/upgrade/upgrade.spec.ts
  packages/cli/src/generate/generators/upgrade/upgrade.ts
  packages/cli/src/generate/utils/index.ts
  packages/cli/src/generate/utils/install-dependencies.ts
  packages/cli/src/generate/utils/logger.ts
  packages/cli/src/index.ts
  packages/cli/typings/node-fetch/index.d.ts
Labels: feature

#1194 Support custom OpenAPI "example" keyword in AJV validation
  docs/blog/version-3.1-release-notes.md
  packages/core/src/common/validation/get-ajv-instance.spec.ts
  packages/core/src/common/validation/get-ajv-instance.ts
Labels: bug
