Repository FoalTS/foal, pull requests merged in 2022-08, with the labels that each got.

#1116 [Website] Upgrade docs to Docusaurus v2 (stable version)
  .github/workflows/documentation.yml
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/src/pages/index.module.scss
  docs/src/theme/BlogPostItem/index.js
  docs/src/theme/BlogPostItem/styles.module.css
  docs/src/theme/TOC/index.js
  docs/src/theme/TOC/styles.module.css
Labels: docs

#1117 Be stricter on some class properties accessors.
  packages/core/src/core/http/context.ts
  packages/core/src/core/http/http-responses.ts
  packages/core/src/sessions/session-store.ts
  packages/jwt/src/invalid-token.error.ts
  packages/socket.io/src/architecture/websocket-context.ts
  packages/storage/src/disk.service.ts
Labels: enhancement, Breaking change, v3

#1118 [CLI] Remove use of `http` module from app bootstrap
  docs/docs/cookbook/limit-repeated-requests.md
  docs/docs/websockets.md
  packages/acceptance-tests/src/docs/cookbook/limit-repeated-requests.spec.ts
  packages/cli/src/generate/specs/app/src/index.ts
  packages/cli/src/generate/templates/app/src/index.ts
  packages/examples/src/index.ts
Labels: enhancement

#1121 Make `PermissionRequired` independent from TypeORM
  docs/docs/authentication-and-access-control/groups-and-permissions.md
  packages/acceptance-tests/src/additional/authorization/groups-and-permissions.spec.ts
  packages/core/src/common/index.ts
  packages/core/src/common/permissions/index.ts
  packages/core/src/common/permissions/permission-required.hook.spec.ts
  packages/core/src/common/permissions/permission-required.hook.ts
  packages/core/src/common/permissions/user-with-permissions.interface.ts
  packages/core/src/index.ts
  packages/typeorm/src/entities/user-with-permissions.entity.ts
  packages/typeorm/src/hooks/index.ts
  packages/typeorm/src/index.ts
Labels: enhancement, Breaking change, v3

#1122 Re-organize common/ internal directory
  packages/acceptance-tests/src/docs/common/validation-and-sanitization/returning-custom-validation-error-messages.feature.ts
  packages/core/copy-debug-page.js
  packages/core/src/common/auth/access/index.ts
  packages/core/src/common/auth/access/user-required.hook.spec.ts
  packages/core/src/common/auth/access/user-required.hook.ts
  packages/core/src/common/auth/index.ts
  packages/core/src/common/auth/passwords/hash-password.spec.ts
  packages/core/src/common/auth/passwords/hash-password.ts
  packages/core/src/common/auth/passwords/index.ts
  packages/core/src/common/auth/passwords/verify-password.spec.ts
  packages/core/src/common/auth/passwords/verify-password.ts
  packages/core/src/common/index.ts
  packages/core/src/common/templates/500.debug.html
  packages/core/src/common/templates/index.ts
  packages/core/src/common/templates/render-error.spec.ts
  packages/core/src/common/templates/render-error.ts
  packages/core/src/common/templates/render.spec.ts
  packages/core/src/common/templates/render.ts
  packages/core/src/common/utils/index.ts
  packages/core/src/common/utils/log.hook.spec.ts
  packages/core/src/common/utils/log.hook.ts
  packages/core/src/common/validation/get-ajv-instance.spec.ts
  packages/core/src/common/validation/get-ajv-instance.ts
  packages/core/src/common/validation/helpers/index.ts
  packages/core/src/common/validation/helpers/is-function.util.ts
  packages/core/src/common/validation/index.ts
  packages/core/src/common/validation/validate-body.hook.spec.ts
  packages/core/src/common/validation/validate-body.hook.ts
  packages/core/src/common/validation/validate-cookie.hook.spec.ts
  packages/core/src/common/validation/validate-cookie.hook.ts
  packages/core/src/common/validation/validate-header.hook.spec.ts
  packages/core/src/common/validation/validate-header.hook.ts
  packages/core/src/common/validation/validate-path-param.hook.spec.ts
  packages/core/src/common/validation/validate-path-param.hook.ts
  packages/core/src/common/validation/validate-query-param.hook.spec.ts
  packages/core/src/common/validation/validate-query-param.hook.ts
Labels: enhancement, internal

#1123 Fix concurrently issue on some OS
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
Labels: bug

#1124 Replace `foal g vscode-config` with documentation
  docs/docs/development-environment/vscode.md
  packages/cli/src/generate/fixtures/vscode-config/package.json
  packages/cli/src/generate/generators/index.ts
  packages/cli/src/generate/generators/vscode-config/create-vscode-config.spec.ts
  packages/cli/src/generate/generators/vscode-config/create-vscode-config.ts
  packages/cli/src/generate/generators/vscode-config/index.ts
  packages/cli/src/generate/specs/vscode-config/launch.json
  packages/cli/src/generate/specs/vscode-config/tasks.json
  packages/cli/src/generate/templates/vscode-config/launch.json
  packages/cli/src/generate/templates/vscode-config/tasks.json
  packages/cli/src/index.ts
Labels: Breaking change, v3

#1125 Remove `@foal/password` package
  .github/workflows/test.yml
  docs/docs/authentication-and-access-control/password-management.md
  docs/docs/authentication-and-access-control/user-class.md
  docs/docs/community/awesome-foal.md
  packages/password/LICENSE
  packages/password/README.md
  packages/password/package-lock.json
  packages/password/package.json
  packages/password/src/10-million-password-list-top-10000.txt.gz
  packages/password/src/index.ts
  packages/password/src/is-common.util.spec.ts
  packages/password/src/is-common.util.ts
  packages/password/tsconfig-build.json
  packages/password/tsconfig.json
Labels: Breaking change, v3

#1119 Add `userIdType` option to `@JWT` and `@UseSessions` and remove `fetchUser` interface and functions
  docs/docs/api-section/graphql.md
  docs/docs/authentication-and-access-control/groups-and-permissions.md
  docs/docs/authentication-and-access-control/jwt.md
  docs/docs/authentication-and-access-control/quick-start.md
  docs/docs/authentication-and-access-control/session-tokens.md
  docs/docs/databases/mongodb.md
  docs/docs/databases/using-another-orm.md
  docs/docs/tutorials/real-world-example-with-react/10-auth-with-react.md
  docs/docs/tutorials/real-world-example-with-react/8-authentication.md
  packages/acceptance-tests/src/additional/authorization/groups-and-permissions.spec.ts
  packages/acceptance-tests/src/additional/typeorm.mongodb-store.spec.ts
  packages/acceptance-tests/src/additional/typeorm.redis-store.spec.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/administrators-and-roles/controlling-access-with-administrators.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/administrators-and-roles/controlling-access-with-static-roles.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-spa-using-cookies.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-spa-using-header.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-ssr-app-using-cookies.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateless-spa-using-cookies.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateless-spa-using-header.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/adding-authentication-and-access-control.feature.ts
  packages/acceptance-tests/src/docs/databases/using-another-orm/creating-a-custom-fetch-user-function.feature.ts
  packages/cli/src/generate/specs/app/src/app/entities/user.entity.mongodb.ts
  packages/cli/src/generate/specs/entity/test-foo-bar.entity.mongodb.ts
  packages/cli/src/generate/templates/app/src/app/entities/user.entity.mongodb.ts
  packages/cli/src/generate/templates/entity/entity.mongodb.ts
  packages/core/src/index.ts
  packages/core/src/sessions/fetch-user.interface.ts
  packages/core/src/sessions/http/check-user-id-type.spec.ts
  packages/core/src/sessions/http/check-user-id-type.ts
  packages/core/src/sessions/http/get-session-id-from-request.spec.ts
  packages/core/src/sessions/http/get-session-id-from-request.ts
  packages/core/src/sessions/index.ts
  packages/core/src/sessions/use-sessions.hook.spec.ts
  packages/core/src/sessions/use-sessions.hook.ts
  packages/jwt/src/http/check-and-convert-user-id-type.spec.ts
  packages/jwt/src/http/check-and-convert-user-id-type.ts
  packages/jwt/src/jwt-optional.hook.ts
  packages/jwt/src/jwt-required.hook.ts
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
  packages/typeorm/src/entities/user-with-permissions.entity.ts
  packages/typeorm/src/index.ts
  packages/typeorm/src/utils/fetch-mongodb-user.util.spec.ts
  packages/typeorm/src/utils/fetch-mongodb-user.util.ts
  packages/typeorm/src/utils/fetch-user-with-permissions.util.spec.ts
  packages/typeorm/src/utils/fetch-user-with-permissions.util.ts
  packages/typeorm/src/utils/fetch-user.util.spec.ts
  packages/typeorm/src/utils/fetch-user.util.ts
  packages/typeorm/src/utils/index.ts
Labels: enhancement, Breaking change, v3

#1127 Rename "npm run develop" to "npm run dev"
  README.md
  docs/docs/README.md
  docs/docs/api-section/gRPC.md
  docs/docs/api-section/graphql.md
  docs/docs/development-environment/build-and-start-the-app.md
  docs/docs/development-environment/create-and-run-scripts.md
  docs/docs/tutorials/real-world-example-with-react/1-introduction.md
  docs/docs/tutorials/real-world-example-with-react/14-production-build.md
  docs/docs/tutorials/simple-todo-list/1-installation.md
  packages/cli/src/generate/generators/app/create-app.ts
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
  packages/cli/src/run-script/run-script.spec.ts
  packages/cli/src/run-script/run-script.ts
  packages/examples/package.json
Labels: enhancement, Breaking change, v3

#1129 Do not throw on uploads with empty filenames
  packages/storage/src/local-disk.service.ts
  packages/storage/src/validate-multipart-form-data-body.hook.spec.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
Labels: enhancement

#1128 Fix issue #1021 to take an env var over a .env-file variable.
  docs/docs/architecture/configuration.md
  packages/core/src/core/config/env.spec.ts
  packages/core/src/core/config/env.ts
Labels: Breaking change, v3

#1048 Simplify `ValidateMultipartFormDataBody` and support optional fields
  docs/docs/file-system/upload-and-download-files.md
  docs/docs/tutorials/real-world-example-with-react/12-file-upload.md
  docs/docs/tutorials/simple-todo-list/1-installation.md
  packages/acceptance-tests/package.json
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/adding-fields-in-file-uploads.feature.ts
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/assets/image.test.png
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/assets/image.test2.png
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/downloading-files.feature.ts
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/uploading-and-downloading-files-with-a-db.feature.ts
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/using-buffers-in-file-uploads.feature.ts
  packages/acceptance-tests/src/docs/file-system/upload-and-download-files/using-streaming-in-file-uploads.feature.ts
  packages/core/src/common/file/file-list.spec.ts
  packages/core/src/common/file/file-list.ts
  packages/core/src/common/file/file.spec.ts
  packages/core/src/common/file/file.ts
  packages/core/src/common/file/index.ts
  packages/core/src/common/index.ts
  packages/core/src/core/http/context.spec.ts
  packages/core/src/core/http/context.ts
  packages/core/src/index.ts
  packages/examples/src/app/controllers/profile.controller.ts
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/storage/src/index.ts
  packages/storage/src/local-disk.service.ts
  packages/storage/src/parse-and-validate-files.hook.spec.ts
  packages/storage/src/parse-and-validate-files.hook.ts
  packages/storage/src/validate-multipart-form-data-body.hook.ts
Labels: Breaking change, v3

#1133 [Sessions] Split the directory `sessions/` into `sessions/core` and `session/http`
  packages/core/src/sessions/core/constants.ts
  packages/core/src/sessions/core/create-session.spec.ts
  packages/core/src/sessions/core/create-session.ts
  packages/core/src/sessions/core/read-session.spec.ts
  packages/core/src/sessions/core/read-session.ts
  packages/core/src/sessions/core/session-state.interface.ts
  packages/core/src/sessions/core/session-store.spec.ts
  packages/core/src/sessions/core/session-store.ts
  packages/core/src/sessions/core/session.spec.ts
  packages/core/src/sessions/core/session.ts
  packages/core/src/sessions/http/constants.ts
  packages/core/src/sessions/http/get-session-id-from-request.spec.ts
  packages/core/src/sessions/http/get-session-id-from-request.ts
  packages/core/src/sessions/http/remove-session-cookie.spec.ts
  packages/core/src/sessions/http/remove-session-cookie.ts
  packages/core/src/sessions/http/set-session-cookie.spec.ts
  packages/core/src/sessions/http/set-session-cookie.ts
  packages/core/src/sessions/http/use-sessions.hook.spec.ts
  packages/core/src/sessions/http/use-sessions.hook.ts
  packages/core/src/sessions/index.ts
Labels: internal, v3

#1134 Add `getCsrfTokenFromRequest` util
  packages/core/src/sessions/http/get-csrf-token-from-request.spec.ts
  packages/core/src/sessions/http/get-csrf-token-from-request.ts
  packages/core/src/sessions/http/use-sessions.hook.spec.ts
  packages/core/src/sessions/http/use-sessions.hook.ts
  packages/jwt/src/http/get-csrf-token-from-request.spec.ts
  packages/jwt/src/http/get-csrf-token-from-request.ts
  packages/jwt/src/jwt.hook.spec.ts
  packages/jwt/src/jwt.hook.ts
Labels: enhancement, v3

#1135 [JWT] Split the directory `jwt/` into `jwt/core` and `jwt/http`
  packages/jwt/src/core/get-secret-or-private-key.util.spec.ts
  packages/jwt/src/core/get-secret-or-private-key.util.ts
  packages/jwt/src/core/get-secret-or-public-key.util.spec.ts
  packages/jwt/src/core/get-secret-or-public-key.util.ts
  packages/jwt/src/core/invalid-token.error.spec.ts
  packages/jwt/src/core/invalid-token.error.ts
  packages/jwt/src/http/constants.ts
  packages/jwt/src/http/get-jwt-from-request.spec.ts
  packages/jwt/src/http/get-jwt-from-request.ts
  packages/jwt/src/http/jwt-optional.hook.spec.ts
  packages/jwt/src/http/jwt-optional.hook.ts
  packages/jwt/src/http/jwt-required.hook.spec.ts
  packages/jwt/src/http/jwt-required.hook.ts
  packages/jwt/src/http/jwt.hook.spec.ts
  packages/jwt/src/http/jwt.hook.ts
  packages/jwt/src/http/remove-auth-cookie.spec.ts
  packages/jwt/src/http/remove-auth-cookie.ts
  packages/jwt/src/http/set-auth-cookie.spec.ts
  packages/jwt/src/http/set-auth-cookie.ts
  packages/jwt/src/index.ts
Labels: internal, v3

#1138 Add `getCsrfTokenFromRequest` util
  packages/core/src/sessions/http/get-csrf-token-from-request.spec.ts
  packages/core/src/sessions/http/get-csrf-token-from-request.ts
  packages/core/src/sessions/http/use-sessions.hook.spec.ts
  packages/core/src/sessions/http/use-sessions.hook.ts
  packages/jwt/src/http/get-csrf-token-from-request.spec.ts
  packages/jwt/src/http/get-csrf-token-from-request.ts
  packages/jwt/src/http/jwt.hook.spec.ts
  packages/jwt/src/http/jwt.hook.ts
Labels: enhancement, internal

#1140 Add `getCsrfTokenFromCookie` and `shouldVerifyCsrfToken` utils
  packages/core/src/sessions/http/use-sessions.hook.spec.ts
  packages/core/src/sessions/http/use-sessions.hook.ts
  packages/core/src/sessions/http/utils/index.ts
  packages/core/src/sessions/http/utils/should-verify-csrf-token.spec.ts
  packages/core/src/sessions/http/utils/should-verify-csrf-token.ts
  packages/jwt/src/http/jwt.hook.spec.ts
  packages/jwt/src/http/jwt.hook.ts
  packages/jwt/src/http/utils/get-csrf-token-from-cookie.spec.ts
  packages/jwt/src/http/utils/get-csrf-token-from-cookie.ts
  packages/jwt/src/http/utils/index.ts
  packages/jwt/src/http/utils/should-verify-csrf-token.spec.ts
  packages/jwt/src/http/utils/should-verify-csrf-token.ts
Labels: enhancement, internal

#1141 Reorganize utils in `jwt/` and `sessions/`
  packages/core/src/sessions/http/use-sessions.hook.ts
  packages/core/src/sessions/http/utils/get-csrf-token-from-request.spec.ts
  packages/core/src/sessions/http/utils/get-csrf-token-from-request.ts
  packages/core/src/sessions/http/utils/index.ts
  packages/core/src/sessions/http/utils/remove-session-cookie.spec.ts
  packages/core/src/sessions/http/utils/remove-session-cookie.ts
  packages/core/src/sessions/http/utils/set-session-cookie.spec.ts
  packages/core/src/sessions/http/utils/set-session-cookie.ts
  packages/jwt/src/http/jwt.hook.ts
  packages/jwt/src/http/utils/get-csrf-token-from-request.spec.ts
  packages/jwt/src/http/utils/get-csrf-token-from-request.ts
  packages/jwt/src/http/utils/index.ts
Labels: enhancement, internal

#1143 [Website] Prepare landing page structure to add company logs
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/src/css/custom.scss
  docs/src/pages/index.jsx
  docs/src/pages/index.module.scss
  docs/tailwind.config.js
Labels: docs

#1145 Move `createSession` and `readSession` to session stores
  docs/docs/authentication-and-access-control/quick-start.md
  docs/docs/authentication-and-access-control/session-tokens.md
  docs/docs/security/csrf-protection.md
  packages/acceptance-tests/e2e_db.sqlite-shm
  packages/acceptance-tests/e2e_db.sqlite-wal
  packages/acceptance-tests/src/additional/authentication/do-not-save-sessions-on-error.spec.ts
  packages/acceptance-tests/src/additional/authentication/isolate-sessions-from-each-other.spec.ts
  packages/acceptance-tests/src/additional/authorization/groups-and-permissions.spec.ts
  packages/acceptance-tests/src/additional/session.config.spec.ts
  packages/acceptance-tests/src/additional/typeorm.mongodb-store.spec.ts
  packages/acceptance-tests/src/additional/typeorm.redis-store.spec.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/administrators-and-roles/controlling-access-with-administrators.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/administrators-and-roles/controlling-access-with-static-roles.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/quick-start/authenticating-users-in-a-stateful-spa-using-header.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/adding-authentication-and-access-control.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/destroying-the-session.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/do-not-auto-create-the-session.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/modifying-session-timeouts.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/providing-a-custom-client-to-use-in-stores.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/reading-a-session-from-a-token.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/regenerating-the-session-id.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/revoking-sessions.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/saving-and-reading-content.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/specifying-the-store-locally.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/using-cookies.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/session-tokens/using-the-authorization-header.feature.ts
  packages/acceptance-tests/src/docs/authentication-and-access-control/social-auth/using-social-auth-with-sessions.feature.ts
  packages/acceptance-tests/src/docs/security/csrf/regular-web-app.stateful.spec.ts
  packages/acceptance-tests/src/docs/security/csrf/spa.stateful.spec.ts
  packages/core/src/index.ts
  packages/core/src/sessions/core/create-session.spec.ts
  packages/core/src/sessions/core/create-session.ts
  packages/core/src/sessions/core/index.ts
  packages/core/src/sessions/core/read-session.spec.ts
  packages/core/src/sessions/core/read-session.ts
  packages/core/src/sessions/core/session-store.spec.ts
  packages/core/src/sessions/core/session-store.ts
  packages/core/src/sessions/http/use-sessions.hook.spec.ts
  packages/core/src/sessions/http/use-sessions.hook.ts
  packages/core/src/sessions/http/utils/check-user-id-type.spec.ts
  packages/core/src/sessions/http/utils/check-user-id-type.ts
  packages/core/src/sessions/http/utils/get-session-id-from-request.spec.ts
  packages/core/src/sessions/http/utils/get-session-id-from-request.ts
  packages/core/src/sessions/http/utils/index.ts
  packages/core/src/sessions/index.ts
  packages/jwt/src/http/jwt.hook.ts
  packages/jwt/src/http/utils/check-and-convert-user-id-type.spec.ts
  packages/jwt/src/http/utils/check-and-convert-user-id-type.ts
  packages/jwt/src/http/utils/get-jwt-from-request.spec.ts
  packages/jwt/src/http/utils/get-jwt-from-request.ts
  packages/jwt/src/http/utils/index.ts
  packages/mongodb/src/mongodb-store.service.spec.ts
  packages/redis/src/redis-store.service.spec.ts
  packages/typeorm/src/typeorm-store.service.spec.ts
Labels: Breaking change, v3
