Repository FoalTS/foal, pull requests merged in 2022-07, with the labels that each got.

#1101 [Website] Update landing page based on FoalTS survey 2022
  docs/docusaurus.config.js
  docs/src/pages/index.jsx
  package.json
  packages/core/package.json
Labels: docs

#1102 [Docs] correct grammar `administrators-and-roles` doc
  docs/docs/authentication-and-access-control/administrators-and-roles.md
Labels: docs

#1107 [Cleanup] Move http request read from `@JWT` and `@UseSessions` into separate functions
  packages/core/src/sessions/http/get-session-id-from-request.spec.ts
  packages/core/src/sessions/http/get-session-id-from-request.ts
  packages/core/src/sessions/use-sessions.hook.ts
  packages/jwt/src/http/get-jwt-from-request.spec.ts
  packages/jwt/src/http/get-jwt-from-request.ts
  packages/jwt/src/jwt.hook.ts
Labels: v3

#1108 Add `User.findOneWithPermissionsBy`
  packages/typeorm/src/entities/user-with-permissions.entity.spec.ts
  packages/typeorm/src/entities/user-with-permissions.entity.ts
Labels: feature, v3

#1109 Adds @foal/cli to package.json templates
  packages/cli/src/generate/specs/app/package.json
  packages/cli/src/generate/specs/app/package.mongodb.json
  packages/cli/src/generate/specs/app/package.mongodb.yaml.json
  packages/cli/src/generate/specs/app/package.yaml.json
  packages/cli/src/generate/templates/app/package.json
  packages/cli/src/generate/templates/app/package.mongodb.json
  packages/cli/src/generate/templates/app/package.mongodb.yaml.json
  packages/cli/src/generate/templates/app/package.yaml.json
Labels: enhancement

#1111 Add `fs.getProjectDependencies` and `fs.getProjectDevDependencies`
  packages/cli/src/generate/file-system.spec.ts
  packages/cli/src/generate/file-system.ts
Labels: enhancement, internal

#1113 Do not let "undefined" values override other config values
  packages/core/src/core/config/config.spec.ts
  packages/core/src/core/config/config.ts
Labels: enhancement, Breaking change, v3
